<?php
require_once 'PHPUnit/Framework.php';

require_once '../_start.php';
require_once '../../../../../_start.php';

/**
 * Test class for CorujaDebug.
 * Generated by PHPUnit on 2008-10-23 at 21:41:23.
 */
class CorujaDebugTest extends PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testDebug().
     */
    public function testDebug() {

        
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * Testing debug with the exit parameter true
     */
    public function testDebugWithExitTrue() {

        CorujaDebug::debug("test",true);

        $this->expectOutputRegex(".*D I E.*");
        
    }
}
?>
