<?php
/*
 * @package public
 * Page Header
 */

/**
 * Page Header has the meta pags what will be shared into all the
 * Code To Diagram Public Pages
 */
?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="author" content="Code To Diagram"/>
<meta http-equiv="content-language" content="en-US"/>
<meta name="description" content="Uml Sequence Diagram automatically generated by Code To Diagram Project"/>
<meta name="keywords" content="uml sequence diagram code to diagram php xml"/>
<meta name="robots" content="Follow"/>
<meta name="verify-v1" content="g0fCoZ1M2qg1BApLira/PHC6jfkUzWenYdFz3Zlj/TU=" />
