CodeToDiagram: CodeInstrumentationReceiver Class Reference
CodeInstrumentationReceiver Class Reference
Public Member Functions
setIgnoreNullReturns ($booIgnoreNullReturns)
getIgnoreNullReturns ()
setIgnoreRecursiveCalls ($booIgnoreRecursiveCalls)
getIgnoreRecursiveCalls ()
setCallerPath ($strCallerPath)
getCallerPath ()
setPublicPath ($strPublicPath)
getPublicPath ()
__construct ()
renameMethod ($strMethod)
onEnterMethod ($uid, $strClassDefinition, $strMethod, $arrArguments)
onLeaveMethod ($uid, $strClassDefinition, $strMethod, $mixReturn)
getXmlSequence ()
restart ()
Static Public Member Functions
static getInstance ()
Static Public Attributes
static $objCodeInstrumentationReceiver
Protected Attributes
$booIgnoreNullReturns = true
$booIgnoreRecursiveCalls = false
$booMergeSameClassObjects = false
$arrStack = array()
$arrActors = array()
$arrClasses = array()
$arrMessages = array()
$objXmlSequence = null
Detailed Description
Class create to make possible the creation of code instrumentation of executions.
It receive the messages of enter methods and leave methods, into what object, of what class and, based into this informations, create a xmlSequence object.
The xml sequence object created, can be used for many ways, since create a xml, create a diagram file, etc.
Todo:
make filter methods to reduce the diagram of big executions
See also:
CodeInstrumentationMethod
CodeInstrumentationClass
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 22 of file CodeInstrumentationReceiver.class.php.
Constructor & Destructor Documentation
__construct ()
prepare the code instrumentation receiver to start to receive the informations about the execution.
1. create the xml sequence object 2. create the user actor
Returns:
null
Definition at line 206 of file CodeInstrumentationReceiver.class.php.
Referenced by restart().
    {
        // 1. create the xml sequence object //
        $this->objXmlSequence = new XmlSequence();
        // 2. create the user actor //
        $objActorFrom = new XmlSequenceActor();
        $objActorFrom->setType( 'user' );
        $objActorFrom->setName( "user" );
        $objActorFrom->setId( sizeof( $this->arrActors ) + 1 );
        $this->arrActors[] = $objActorFrom;
        $this->arrStack[] = $objActorFrom;
        $this->objXmlSequence->addActor($objActorFrom);
    }
Member Function Documentation
getCallerPath ()
Get the caller path of the xml sequence of the code instrumentation receiver
See also:
XmlSequence::getCallerPath
Returns:
string
Definition at line 168 of file CodeInstrumentationReceiver.class.php.
    {
        return $this->objXmlSequence->getCallerPath();
    }
getIgnoreNullReturns ()
get the configuration paramenter if the code instrumentation should ignore the returns messages with null value returned.
See also:
CodeInstrumentationReceiver->boolIgnoreNullReturns
CodeInstrumentationReceiver::seIgnoreNullReturns(boolean)
Returns:
boolean true if should ignore the null returns
Definition at line 115 of file CodeInstrumentationReceiver.class.php.
    {
        return $this->booIgnoreNullReturns;
    }
getIgnoreRecursiveCalls ()
get the configuration paramenter if the code instrumentation should ignore the recursive messages.
See also:
CodeInstrumentationReceiver->booIgnoreRecursiveCalls
CodeInstrumentationReceiver::setIgnoreRecursiveCalls(boolean)
Parameters:
$booIgnoreNullReturns true if should ignore the null returns
Returns:
boolean true if should ignore the recursive calls
Definition at line 144 of file CodeInstrumentationReceiver.class.php.
    {
        return $this->booIgnoreRecursiveCalls;
    }
static getInstance () [static]
Get the code instrumentation receiver singleton
Returns:
CodeInstrumentationReceiver
Definition at line 227 of file CodeInstrumentationReceiver.class.php.
    {
        if( self::$objCodeInstrumentationReceiver ==  null )
        {
            self::$objCodeInstrumentationReceiver = new CodeInstrumentationReceiver();
        }
        return self::$objCodeInstrumentationReceiver;
    }
getPublicPath ()
Get the public path of the xml sequence of the code instrumentation receiver
See also:
XmlSequence::getPublicPath
Returns:
string
Definition at line 192 of file CodeInstrumentationReceiver.class.php.
    {
        return $this->objXmlSequence->getPublicPath();
    }
getXmlSequence ()
Return the Xml Sequence Object what the Code Instrumentation Receiver feeds
Returns:
XmlSequence
Definition at line 425 of file CodeInstrumentationReceiver.class.php.
    {
        return $this->objXmlSequence;
    }
onEnterMethod ($ uid, $ strClassDefinition, $ strMethod, $ arrArguments)
Receive a message of enter into some method and append it as a xml sequence message into the xml sequence object, creating if necessary the xml sequence actor
1. get the name of method as the diagram standart 2. get the namespace name 3. get the actor what the message is bring from 4. get the actor what the message is bring to 4.1 create the actor to if he not exists 5. create the message 5.1 set the message attributes 5.2 set the message values 6. append the message
Parameters:
string $uid
string $strClassDefinition
string $strMethod
Array $arrArguments
Returns:
CodeInstrumentationReceiver me
Definition at line 293 of file CodeInstrumentationReceiver.class.php.
References CorujaClassManipulation::getClassNameFromClassDefinition(), CorujaClassManipulation::getNamespaceFromClassDefinition(), and renameMethod().
    {
        // 1. get the name of method as the diagram standart //
        $strClass               = CorujaClassManipulation::getClassNameFromClassDefinition( $strClassDefinition );
        $arrMethod      = explode( "::" , $strMethod );
        $strMethod              = array_pop( $arrMethod );
        $strMethod      = $this->renameMethod( $strMethod );
        // 2. get the namespace name //
        $strNamespace   = CorujaClassManipulation::getNamespaceFromClassDefinition( $strClassDefinition );
        if( ! array_key_exists( $strClass, $this->arrClasses ) )
        {
            $this->arrClasses[ $strClass ] = 0;
        }
        // 3. get the actor what the message is bring from  //
        $objActorFrom = current( $this->arrStack );
        // 4. get the actor what the message is bring to //
        if( ! array_key_exists( $uid , $this->arrActors ) )
        {
                // 4.1 create the actor to if he not exists //
            $this->arrClasses[ $strClass ]++;
            $objActorTo = new XmlSequenceActor();
            $objActorTo->setType( 'system' );
            $objActorTo->setClassName($strClass);
            $objActorTo->setName( $strClass . '(' . $this->arrClasses[ $strClass ] . ')');
            $objActorTo->setId(sizeof( $this->arrActors ) + 1  );
            $this->arrActors[ $uid ] = $objActorTo;
            $this->objXmlSequence->addActor($objActorTo);
        }
        else
        {
            $objActorTo = $this->arrActors[ $uid ];
        }
        // 5. create the message //
        $objMessage = new XmlSequenceMessage();
        // 5.1 set the message attributes //
        $objMessage->setText( $strMethod );
        $objMessage->setActorFrom( $objActorFrom );
        $objMessage->setActorTo( $objActorTo );
        $objMessage->setType( 'call' );
        // 5.2 set the message values //
        foreach( $arrArguments as $strName => $mixValue )
        {
            $objValue = new XmlSequenceValue();
            $objValue->setName( '[' . $strName  . ']');
            $objValue->setValue( serialize( $mixValue ) );
            $objMessage->addValue( $objValue );
        }
        $objMessage->setTimeStart( microtime( true ) );
        // 6. append the message  //
        $this->objXmlSequence->addMessage( $objMessage );
        $this->arrMessages[]    = $objMessage;
        array_unshift( $this->arrStack , $objActorTo );
        return $this;
    }
onLeaveMethod ($ uid, $ strClassDefinition, $ strMethod, $ mixReturn)
Receive the message of leave some method and append it message into the xml sequence object
1. get the name of method as the diagram standart 2. get the namespace name 3. get the actor what the message is bring from 4. get the actor what the message is bring to 5. create the message 5.1 set the message attributes 5.2 set the message values 6. append the message
Parameters:
integer $uid
string $strClassDefinition
string $strMethod
$mixReturn
Returns:
CodeInstrumentationReceiver me
Definition at line 376 of file CodeInstrumentationReceiver.class.php.
References CorujaClassManipulation::getClassNameFromClassDefinition(), CorujaClassManipulation::getNamespaceFromClassDefinition(), and renameMethod().
    {
        // 1. get the name of method as the diagram standart //
        $strClass               = CorujaClassManipulation::getClassNameFromClassDefinition( $strClassDefinition );
        $arrMethod      = explode( "::" , $strMethod );
        $strMethod              = array_pop( $arrMethod );
        $strMethod      = $this->renameMethod( $strMethod );
        // 2. get the namespace name //
        $strNamespace   = CorujaClassManipulation::getNamespaceFromClassDefinition( $strClassDefinition );
        // 3. get the actor what the message is bring from //
        $objActorFrom = array_shift( $this->arrStack );
        // 4. get the actor what the message is bring to //
        $objActorTo = current( $this->arrStack );
        if( $mixReturn != null or !$this->booIgnoreNullReturns)
        {
                // 5. create the message //
            $objMessage = new XmlSequenceMessage();
            // 5.1 set the message attributes //
            $objMessage->setText( $strMethod );
            $objMessage->setActorFrom( $objActorFrom );
            $objMessage->setActorTo( $objActorTo );
            $objMessage->setType( 'return' );
            // 5.2 set the message values //
            if( $mixReturn !== null )
            {
                $objValue = new XmlSequenceValue();
                $objValue->setName( "[return]" );
                $objValue->setValue( serialize( $mixReturn ) );
                $objMessage->addValue( $objValue );
            }
            // 6. append the message  //
            $this->objXmlSequence->addMessage( $objMessage );
            $objMessage->setTimeEnd( microtime( true ) );
        }
        return $this;
    }
renameMethod ($ strMethod)
Rename the method to which they are in accordance with the standarts of the diagram
1. if __construct replace by <<create>> 2. if __destruct replace by <<destroy>> 3. other cases should append the "()"
Parameters:
string $strMethod old method name
Returns:
string new method name
Definition at line 247 of file CodeInstrumentationReceiver.class.php.
Referenced by onEnterMethod(), and onLeaveMethod().
    {
        switch( $strMethod )
        {
                // 1. if __construct replace by <<create>> //
            case "__construct":
            {
                $strMethod = htmlentities( "<<create>>" );
                break;
            }
            // 2. if __destruct replace by <<destroy>> //
            case "__destruct":
            {
                $strMethod = htmlentities( "<<destroy>>" );
                break;
            }
            // 3. other cases should append the "()" //
            default:
            {
                $strMethod .= "()";
                break;
            }
        }
        return $strMethod;
    }
restart ()
Clean the attributes of the xml sequence existing
1. clean actors 2. clean classes 3. clean messages 4. clean stack 5. clean object xml sequence 6. restart the receiver
Returns:
CodeInstrumentationReceiver
Definition at line 442 of file CodeInstrumentationReceiver.class.php.
References __construct().
    {
        // 1. clean actors //
        $this->arrActors = array();
        // 2. clean classes //
        $this->arrClasses = array();
        // 3. clean messages //
        $this->arrMessages = array();
        // 4. clean stack //
        $this->arrStack = array();
        // 5. clean object xml sequence //
        $this->objXmlSequence->restart();
        // 6. restart the receiver //
        $this->__construct();
        return $this;
    }
setCallerPath ($ strCallerPath)
Set the caller path of the xml sequence of the code instrumentation receiver
See also:
XmlSequence::setCallerPath
Parameters:
string $strCallerPath
Returns:
CodeInstrumentationReceiver me
Definition at line 156 of file CodeInstrumentationReceiver.class.php.
    {
        $this->objXmlSequence->setCallerPath( $strCallerPath );
        return $this;
    }
setIgnoreNullReturns ($ booIgnoreNullReturns)
Set the configuration paramenter if the code instrumentation should ignore the returns messages with null value returned.
See also:
CodeInstrumentationReceiver->boolIgnoreNullReturns
CodeInstrumentationReceiver::geIgnoreNullReturns()
Parameters:
$booIgnoreNullReturns true if should ignore the null returns
Returns:
CodeInstrumentationReceiver me
Definition at line 101 of file CodeInstrumentationReceiver.class.php.
References $booIgnoreNullReturns.
    {
        $this->booIgnoreNullReturns = $booIgnoreNullReturns;
        return $this;
    }
setIgnoreRecursiveCalls ($ booIgnoreRecursiveCalls)
Set the configuration paramenter if the code instrumentation should ignore the recursive messages.
See also:
CodeInstrumentationReceiver->booIgnoreRecursiveCalls
CodeInstrumentationReceiver::getIgnoreRecursiveCalls()
Parameters:
$booIgnoreNullReturns true if should ignore the recursive calls
Returns:
CodeInstrumentationReceiver me
Definition at line 129 of file CodeInstrumentationReceiver.class.php.
References $booIgnoreRecursiveCalls.
    {
        $this->booIgnoreRecursiveCalls = $booIgnoreRecursiveCalls;
        return $this;
    }
setPublicPath ($ strPublicPath)
Set the public path of the xml sequence of the code instrumentation receiver
See also:
XmlSequence::setPublicPath
Parameters:
string $strPublicPath
Returns:
CodeInstrumentationReceiver me
Definition at line 180 of file CodeInstrumentationReceiver.class.php.
    {
        $this->objXmlSequence->setPublicPath( $strPublicPath );
        return $this;
    }
Member Data Documentation
$arrActors = array() [protected]
array with all the actors existents into the execution
XmlSequenceActor[]
Definition at line 69 of file CodeInstrumentationReceiver.class.php.
$arrClasses = array() [protected]
Array with the name of all the classes existents into the execution
String[]
Definition at line 76 of file CodeInstrumentationReceiver.class.php.
$arrMessages = array() [protected]
Array with all the messages received into the execution
XmlSequenceMessage[]
Definition at line 83 of file CodeInstrumentationReceiver.class.php.
$arrStack = array() [protected]
stack of actors into the execution pile
XmlSequenceActor[]
Definition at line 62 of file CodeInstrumentationReceiver.class.php.
$booIgnoreNullReturns = true [protected]
param if the null return should be saved as a message into the xml sequence object
boolean
Definition at line 37 of file CodeInstrumentationReceiver.class.php.
Referenced by setIgnoreNullReturns().
$booIgnoreRecursiveCalls = false [protected]
param if the recursive call should be ignored into the xml sequence object
boolean
Definition at line 45 of file CodeInstrumentationReceiver.class.php.
Referenced by setIgnoreRecursiveCalls().
$booMergeSameClassObjects = false [protected]
param of control if the messages between objects of the same class should be saved into the xml sequence object as recursive calls into the same object
boolean
Definition at line 55 of file CodeInstrumentationReceiver.class.php.
$objCodeInstrumentationReceiver [static]
singletoon of the CodeInstrumentationReceiver
CodeInstrumentationReceiver
Definition at line 29 of file CodeInstrumentationReceiver.class.php.
$objXmlSequence = null [protected]
Object of the xml sequence what will be feed into the execution
XmlSequence
Definition at line 90 of file CodeInstrumentationReceiver.class.php.
The documentation for this class was generated from the following file:
components/codeInstrumentation/CodeInstrumentationReceiver.class.php