CodeToDiagram: CorujaClassManipulation Class Reference
CorujaClassManipulation Class Reference
Static Public Member Functions
static getClassNameFromClassDefinition ($strClassDefinition)
static getNamespaceFromClassDefinition ($strClassDefiniton)
Detailed Description
Class for manipulation of classes
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 11 of file CorujaClassManipulation.class.php.
Member Function Documentation
static getClassNameFromClassDefinition ($ strClassDefinition) [static]
Return classe name from class definition
Parameters:
String $strClassDefinition Class definition
Returns:
String Class name
Example:
getClassNameFromClassDefinition("myNamespace::myClass"); // returns "myClass"
Assert:
("myNamespace::myClass") = "myClass"
Assert:
("myClass") = "myClass"
Assert:
("") = ""
Assert:
(null) throws InvalidArgumentException
Assert:
(123) throws InvalidArgumentException
Assert:
(array()) throws InvalidArgumentException
Assert:
(new stdClass()) throws InvalidArgumentException
Assert:
(false) throws InvalidArgumentException
Definition at line 31 of file CorujaClassManipulation.class.php.
Referenced by CodeInstrumentationReceiver::onEnterMethod(), CodeInstrumentationReceiver::onLeaveMethod(), CorujaClassManipulationTest::testGetClassNameFromClassDefinitionWithAnyString(), CorujaClassManipulationTest::testGetClassNameFromClassDefinitionWithNormalClassDefinition(), and CorujaClassManipulationTest::testGetClassNameFromClassDefinitionWithNullString().
        {
                if(!is_string($strClassDefinition))
                {
                        throw new InvalidArgumentException("Invalid argument [ ". var_export($strClassDefinition) ." ]. It should be string");
                }
        $arrClassDefinition = explode( "::" , $strClassDefinition );
                return array_pop( $arrClassDefinition );
        }
static getNamespaceFromClassDefinition ($ strClassDefiniton) [static]
Return namespace from class definition
Parameters:
String $strClassDefinition Class definition
Returns:
String Namespace
Example:
getClassNameFromClassDefinition("myNamespace::myClass"); // returns "myNamespace"
Assert:
("myNamespace::myClass") = "myNamespace"
Assert:
("myClass") = ""
Assert:
("") = ""
Assert:
(null) throws InvalidArgumentException
Assert:
(123) throws InvalidArgumentException
Assert:
(array()) throws InvalidArgumentException
Assert:
(new stdClass()) throws InvalidArgumentException
Assert:
(false) throws InvalidArgumentException
Definition at line 60 of file CorujaClassManipulation.class.php.
References CorujaArrayManipulation::getArrayField().
Referenced by CodeInstrumentationReceiver::onEnterMethod(), CodeInstrumentationReceiver::onLeaveMethod(), CorujaClassManipulationTest::testGetNamespaceFromClassDefinitionWithAnyString(), CorujaClassManipulationTest::testGetNamespaceFromClassDefinitionWithNormalClassDefinition(), and CorujaClassManipulationTest::testGetNamespaceFromClassDefinitionWithNullString().
        {
                if(!is_string($strClassDefiniton))
                {
                        throw new InvalidArgumentException("Invalid argument [ ". var_export($strClassDefiniton) ." ]. It should be string");
                }
                return CorujaArrayManipulation::getArrayField( explode( "::" , $strClassDefiniton )  , 1 , "" );
        }
The documentation for this class was generated from the following file:
components/library/CorujaClassManipulation.class.php