CodeToDiagram: ExtendedReflectionMethod Class Reference
ExtendedReflectionMethod Class Reference
Public Member Functions
getDeclaringClass ()
getParameters ()
Protected Member Functions
createExtendedReflectionClass (ReflectionClass $objOriginalReflectionClass)
createExtendedReflectionParameter (ReflectionParameter $objReflectionParameter)
Detailed Description
Class what make possible and easy extend reflection method
Reflection classes can be a problem because the reflection methods what return objects will return the original reflection object and not the extended version of it. So it is necessary to create methods what convert the original methods to return the extended version of the objects.
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 20 of file ExtendedReflectionMethod.class.php.
Member Function Documentation
createExtendedReflectionClass (ReflectionClass $ objOriginalReflectionClass) [protected]
Convert a reflection class into a extended reflection class
This is the method what should be replaced when this class be extended.
Parameters:
ReflectionClass $objOriginalReflectionClass
Returns:
ExtendedReflectionClass
Reimplemented in CodeInstrumentationMethod, and CodeReflectionMethod.
Definition at line 59 of file ExtendedReflectionMethod.class.php.
Referenced by getDeclaringClass().
        {
                return new ExtendedReflectionClass( $objOriginalReflectionClass->getName() );
        }
createExtendedReflectionParameter (ReflectionParameter $ objReflectionParameter) [protected]
Convert a reflection parameter into a extended reflection parameter
This is the method what should be replaced when this class be extended.
Parameters:
ReflectionParameter $objReflectionParameter
Returns:
ExtendedReflectionParameter
Reimplemented in CodeInstrumentationMethod, and CodeReflectionMethod.
Definition at line 73 of file ExtendedReflectionMethod.class.php.
References getDeclaringClass().
Referenced by getParameters().
        {
                return new ExtendedReflectionParameter( Array( $this->getDeclaringClass()->getName() , $this->getName() ) , $objReflectionParameter->getName() );
        }
getDeclaringClass ()
Get the class owner of the reflected method
Returns:
ExtendedReflectionClass
Definition at line 27 of file ExtendedReflectionMethod.class.php.
References createExtendedReflectionClass().
Referenced by createExtendedReflectionParameter(), CodeReflectionMethod::createExtendedReflectionParameter(), and CodeInstrumentationMethod::createExtendedReflectionParameter().
    {
        $objReflectionClass = parent::getDeclaringClass();
        return $this->createExtendedReflectionClass( $objReflectionClass );
    }
getParameters ()
Get the collection of the parameters of the reflected method
Returns:
ExtendedReflectionParameter[]
Definition at line 38 of file ExtendedReflectionMethod.class.php.
References createExtendedReflectionParameter().
Referenced by CodeReflectionMethod::createParametersCode().
    {
        $arrReflectionParameters = parent::getParameters();
        $arrExtendedParameters = array();
                foreach( $arrReflectionParameters as $objReflectionParameter )
                {
                        /*@var $objReflectionParameter ReflectionParameter */
                        $arrExtendedParameters[] = $this->createExtendedReflectionParameter( $objReflectionParameter );
                }
                return $arrExtendedParameters;
    }
The documentation for this class was generated from the following file:
components/extendedReflection/ExtendedReflectionMethod.class.php