CodeToDiagram: CodeReflectionMethod Class Reference
CodeReflectionMethod Class Reference
Public Member Functions
getCode ()
getCodeContent ()
createMethodHeaderCode ()
Protected Member Functions
createExtendedReflectionClass (ReflectionClass $objOriginalReflectionClass)
createExtendedReflectionParameter (ReflectionParameter $objReflectionParameter)
createModifiersCode ()
createParametersCode ()
createMethodContentCode ()
Detailed Description
Generated the code definition of some method based into its reflection information
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 14 of file CodeReflectionMethod.class.php.
Member Function Documentation
createExtendedReflectionClass (ReflectionClass $ objOriginalReflectionClass) [protected]
Create the link between the code reflection method and its code reflection class
See also:
ExtendedReflectionMethod::createExtendedReflectionClass(ReflectionClass)
Parameters:
ReflectionClass $objOriginalReflectionClass
Returns:
CodeReflectionClass
Reimplemented from ExtendedReflectionMethod.
Reimplemented in CodeInstrumentationMethod.
Definition at line 51 of file CodeReflectionMethod.class.php.
        {
                return new CodeReflectionClass( $objOriginalReflectionClass->getName() );
        }
createExtendedReflectionParameter (ReflectionParameter $ objReflectionParameter) [protected]
Create the link between the code reflection method and its code reflection parameter
See also:
ExtendedReflectionMethod::createExtendedReflectionParameter(ReflectionParameter)
Parameters:
ReflectionParameter $objReflectionParameter
Returns:
CodeReflectionParameter
Reimplemented from ExtendedReflectionMethod.
Reimplemented in CodeInstrumentationMethod.
Definition at line 64 of file CodeReflectionMethod.class.php.
References ExtendedReflectionMethod::getDeclaringClass().
        {
                return new CodeReflectionParameter( Array( $this->getDeclaringClass()->getName() , $this->getName() ) , $objReflectionParameter->getName() );
        }
createMethodContentCode () [protected]
Create the method code definition content
Returns:
string
Reimplemented in CodeInstrumentationMethod.
Definition at line 144 of file CodeReflectionMethod.class.php.
References CodeReflectionFile::getCodeInstrFileName().
Referenced by getCode(), and getCodeContent().
        {
                $strCode = "";
                $strFileName = $this->getFileName();
        $objFile = CodeReflectionFile::getCodeInstrFileName( $strFileName );
        $strCode = $objFile->getFileBit( $this->getStartLine() ,  $this->getEndLine() );
                $strCode = trim( $strCode );
                // remove the { }
                if( $strCode[0] == "{" )
                {
                        $strCode = substr( $strCode , 1 , -1);
                }
                return $strCode;
        }
createMethodHeaderCode ()
Create the method code definition header
Returns:
string
Reimplemented in CodeInstrumentationMethod.
Definition at line 128 of file CodeReflectionMethod.class.php.
References createModifiersCode(), createParametersCode(), and CorujaStringManipulation::retab().
Referenced by getCode().
        {
                $strCode = $this->getDocComment();
                $strCode .= $this->createModifiersCode();
                $strCode .= " function ";
                $strCode .= $this->getName();
                $strCode .= $this->createParametersCode();
                return CorujaStringManipulation::retab( $strCode , 1 );
        }
createModifiersCode () [protected]
Create the modifiers code definition of the method
Returns:
string
Definition at line 74 of file CodeReflectionMethod.class.php.
Referenced by createMethodHeaderCode(), CodeInstrumentationMethod::createMethodHeaderCode(), and CodeInstrumentationMethod::getCallCodeInstrFunctionHeaderCode().
        {
                $strCode = "";
                if( $this->isFinal() )
                {
                        $strCode .= " final ";
                }
                if( $this->isPrivate() )
                {
                        $strCode .= " private ";
                }
                if( $this->isProtected())
                {
                        $strCode .= " protected ";
                }
                if( $this->isPublic())
                {
                        $strCode .= " public ";
                }
                if( $this->isStatic() )
                {
                        $strCode .= " static ";
                }
                return $strCode;
        }
createParametersCode () [protected]
Create the parameters code definition
Returns:
string
Definition at line 105 of file CodeReflectionMethod.class.php.
References ExtendedReflectionMethod::getParameters().
Referenced by createMethodHeaderCode(), CodeInstrumentationMethod::createMethodHeaderCode(), and CodeInstrumentationMethod::getCallCodeInstrFunctionHeaderCode().
        {
                $strCode = "";
                $arrParameters = $this->getParameters();
                $arrParametersName = array();
                foreach(  $arrParameters as $objParameter )
                {
                        /*@var $objParameter CodeReflectionParameter */
                        $arrParametersName[] = $objParameter->getCode();
                }
                $strCode .= "(";
                $strCode .= implode( ", " , $arrParametersName);
                $strCode .= ")";
                return $strCode;
        }
getCode ()
Create the code definition of the reflected method
Returns:
string code method definition
Reimplemented in CodeInstrumentationMethod.
Definition at line 22 of file CodeReflectionMethod.class.php.
References createMethodContentCode(), and createMethodHeaderCode().
        {
                $strCode = "";
                $strCode .= $this->createMethodHeaderCode();
                $strCode .= "{";
                $strCode .= $this->createMethodContentCode();
                $strCode .= "}\n";
                return $strCode;
        }
getCodeContent ()
Get the code content of the method
Returns:
string
Definition at line 38 of file CodeReflectionMethod.class.php.
References createMethodContentCode().
    {
        return $this->createMethodContentCode();
    }
The documentation for this class was generated from the following file:
components/codeReflection/CodeReflectionMethod.class.php