CodeToDiagram: CodeToDiagram Class Reference
CodeToDiagram Class Reference
Public Member Functions
setOutputType ($strType)
getOutputType ()
setStarted ($booStarted)
getStarted ()
setFileFrom ($strFileFrom)
getFileFrom ()
setFileName ($strFileName)
getFileName ()
setCallerPath ($strCallerPath)
getCallerPath ()
setPublicPath ($strPublicPath)
getPublicPath ()
start ()
restart ()
save ()
__destruct ()
addFile ($strFileFrom, $strFile)
CodeToDiagramRequireOnce ($strFileFrom, $strFile)
CodeToDiagramIncludeOnce ($strFileFrom, $strFile)
CodeToDiagramRequire ($strFileFrom, $strFile)
CodeToDiagramInclude ($strFileFrom, $strFile)
CodeToDiagramExit ($strFileFrom, $strMessage= '')
codeInstrumentationLine ($strLine, $strTextSearch)
setCallerPathByFile ($strCallerFile)
Static Public Member Functions
static hasInstance ()
static getInstance ()
static init ($strFile)
Public Attributes
const RUN_IN_FILES = true
const REMOVE_FILES = true
const CODE_TO_DIAGRAM_CLASS_PREFIX = "CTD"
const OUTPUT_TYPE_SCREEN = "screen"
const OUTPUT_TYPE_STRING = "string"
const OUTPUT_TYPE_FILE = "file"
const OUTPUT_TYPE_XML = "xml"
Protected Member Functions
fixFileName ($strFileFrom, $strFile)
hasFile ($strFileFrom, $strFile)
convertFileContent ($strContentFile, $strFile, $strFullFile)
codeInstrumentationClass ($strTextSearch, array &$arrOldClasses, array &$arrNewClasses, array &$arrLines)
preloadFile ($strFileName, $strContentFile)
codeInstrumentationFile ($strFileName, $strContentFile)
loadFile ($strFileFrom, $strFile)
Protected Attributes
$arrFiles = array()
$booStart = false
$strFileFrom = null
$strFileName = null
$strOutputType = self::OUTPUT_TYPE_SCREEN
$strCallerPath
$strPublicPath
Static Protected Attributes
static $objInstance
Detailed Description
Code to diagram master class. Take to itself the service of include and require. Make code instrumentation of all the classes includes making this way possible to wacth some code execution.
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 14 of file CodeToDiagram.class.php.
Constructor & Destructor Documentation
__destruct ()
On destruct it will save the actual diagram any way
Definition at line 467 of file CodeToDiagram.class.php.
References save().
{
       $this->save();
    }
Member Function Documentation
addFile ($ strFileFrom, $ strFile)
Add a file into the code instrumentation process
Parameters:
string $strFileFrom
string $strFile
Returns:
CodeToDiagram
Definition at line 512 of file CodeToDiagram.class.php.
References $strFileFrom, and fixFileName().
Referenced by loadFile().
    {
        $strFile = $this->fixFileName( $strFileFrom, $strFile );
        $this->arrFiles[] = $strFile;
        return $this;
    }
codeInstrumentationClass ($ strTextSearch, array &$ arrOldClasses, array &$ arrNewClasses, array &$ arrLines) [protected]
Implements a code instrumentation into a class
Parameters:
string $strTextSearch
array $arrOldClasses
array $arrNewClasses
array $arrLines
Definition at line 693 of file CodeToDiagram.class.php.
References codeInstrumentationLine().
Referenced by codeInstrumentationFile().
    {
        foreach( $arrLines as $intLine => $strLine )
        {
            $arrResult = $this->codeInstrumentationLine( $strLine , $strTextSearch  );
            if( sizeof( $arrResult ) !== 0 )
            {
                $arrOldClasses[] = $arrResult[ "class_old" ];
                $arrNewClasses[] = $arrResult[ "class_new" ];
                $arrLines[ $intLine ] = $arrResult[ "line" ];
            }
        }
    }
codeInstrumentationFile ($ strFileName, $ strContentFile) [protected]
Implement a code instrumentation into a file
Parameters:
string $strFile
string $strContentFile
the real codeinstrumentation of interfaces fails by mysterious reasons
Definition at line 740 of file CodeToDiagram.class.php.
References $oReflectionCode, $strFileName, $strNewCode, codeInstrumentationClass(), and preloadFile().
Referenced by loadFile().
    {
        $arrLines = explode( "\n"  , $strContentFile );
        $arrOldClasses   = array();
        $arrNewClasses   = array();
        $arrOldInterface = array();
        $arrNewInterface = array();
        $this->codeInstrumentationClass( "class " , $arrOldClasses , $arrNewClasses, $arrLines );
        $this->codeInstrumentationClass( "interface " , $arrOldInterface , $arrNewInterface, $arrLines );
        $strContentFile = implode( "\n" , $arrLines );
        $this->preloadFile( $strFileName , $strContentFile );
        foreach( $arrNewClasses as $intKey => $strNewClassName )
        {
            $oReflectionCode = new CodeInstrumentationClass( $strNewClassName , $strContentFile );
            $oReflectionCode->setClassName( $arrOldClasses[ $intKey ] );
            $strNewCode = $oReflectionCode->getCode();
            if( self::RUN_IN_FILES )
            {
                $strFileName = trim( $strNewClassName ) . "(1).phps";
                file_put_contents( $strFileName , '<?' . 'php ' .  $strNewCode );
                require_once( $strFileName );
                if( self::REMOVE_FILES )
                {
                    unlink( $strFileName );
                }
            }
            else
            {
                eval( $strNewCode );
            }
        }
        foreach( $arrNewInterface as $intKey => $strNewInterfaceName )
        {
            $strOldInterface = $arrOldInterface[ $intKey ];
            $strNewCode = "interface $strOldInterface {} ";
            if( self::RUN_IN_FILES )
            {
                $strFileName = trim( $strNewInterfaceName ) . "(1).phps";
                file_put_contents( $strFileName , '<?' . 'php ' .  $strNewCode );
                require_once( $strFileName );
                if( self::REMOVE_FILES )
                {
                    unlink( $strFileName );
                }
            }
            else
            {
                eval( $strNewCode );
            }
        }
    }
codeInstrumentationLine ($ strLine, $ strTextSearch)
Implement the code instrumentation into a code line
Parameters:
string $strLine
string $strTextSearch
Returns:
array
Definition at line 659 of file CodeToDiagram.class.php.
Referenced by codeInstrumentationClass().
    {
        $arrResult = array();
        if(  substr( strtolower( trim( $strLine ) ) , 0 , strlen( $strTextSearch ) ) == $strTextSearch )
        {
            $strLine = trim( $strLine );
            $strBefore = substr( $strLine , 0 , strlen( $strTextSearch ) );
            $strAfter = substr( $strLine , strlen( $strTextSearch ) );
            $arrWords = explode( " " , $strAfter );
            $strOldClassName = $arrWords[0];
            $strNewClassName = self::CODE_TO_DIAGRAM_CLASS_PREFIX . $strOldClassName;
            $arrWords[0] = $strNewClassName;
            $strAfter = implode( " " , $arrWords );
            $strLine = $strBefore . $strAfter;
            $arrResult[ "line" ] = $strLine;
            $arrResult[ "class_old" ] = $strOldClassName;
            $arrResult[ "class_new" ] = $strNewClassName;
        }
        return $arrResult;
    }
CodeToDiagramExit ($ strFileFrom, $ strMessage = '')
Method what will be called in replace of the original exit function
Parameters:
string $strFileFrom
string $strMessage
Returns:
CodeToDiagram
Definition at line 605 of file CodeToDiagram.class.php.
    {
        print "Exit called into $strFileFrom ($strMessage ) ";
        exit();
    }
CodeToDiagramInclude ($ strFileFrom, $ strFile)
Method what will be called in replace of the original include function
Parameters:
string $strFileFrom
string $strFile
Returns:
CodeToDiagram
Definition at line 591 of file CodeToDiagram.class.php.
References $strFileFrom, and loadFile().
    {
        $this->loadFile( $strFileFrom , $strFile );
        return $this;
    }
CodeToDiagramIncludeOnce ($ strFileFrom, $ strFile)
Method what will be called in replace of the original include_once function
Parameters:
string $strFileFrom
string $strFile
Returns:
CodeToDiagram
Definition at line 560 of file CodeToDiagram.class.php.
References $strFileFrom, and hasFile().
    {
        if( !$this->hasFile( $strFileFrom , $strFile ) )
        {
            $this->CodeToDiagramIncludeOnce( $strFileFrom , $strFile );
        }
        return $this;
    }
CodeToDiagramRequire ($ strFileFrom, $ strFile)
Method what will be called in replace of the original require function
Parameters:
string $strFileFrom
string $strFile
Returns:
CodeToDiagram
Definition at line 577 of file CodeToDiagram.class.php.
References $strFileFrom, and loadFile().
Referenced by CodeToDiagramRequireOnce().
    {
        $this->loadFile( $strFileFrom , $strFile );
        return $this;
    }
CodeToDiagramRequireOnce ($ strFileFrom, $ strFile)
Method what will be called in replace of the original require_once function
Parameters:
string $strFileFrom
string $strFile
Returns:
CodeToDiagram
Definition at line 541 of file CodeToDiagram.class.php.
References $strFileFrom, CodeToDiagramRequire(), and hasFile().
Referenced by start().
    {
        $arrCodeToDiagramBackTrace = debug_backtrace();
        if( !$this->hasFile( $strFileFrom , $strFile ) )
        {
            $this->CodeToDiagramRequire( $strFileFrom, $strFile );
        }
        return $this;
    }
convertFileContent ($ strContentFile, $ strFile, $ strFullFile) [protected]
Replace the php function with the CodeToDiagram function
Parameters:
string $strContentFile
string $strFile
string $strFullFile
Returns:
string
Definition at line 619 of file CodeToDiagram.class.php.
References getCallerPath(), getInstance(), and getStarted().
Referenced by loadFile().
    {
        if( self::getInstance()->getStarted() == false )
        {
            self::getInstance()->setStarted( true );
            $strContentFile = preg_replace('/require_once/', '//require_once', $strContentFile, 1);
        }
        $strContentFile = str_replace(
            Array(
                'require_once(' ,
                'require(' ,
                'include(' ,
                'include_once(',
                'exit()',
                'exit(',
                '__FILE__',
            ),
            Array(
                'CodeToDiagram::getInstance()->CodeToDiagramRequireOnce("'. $strFile . '",' ,
                'CodeToDiagram::getInstance()->CodeToDiagramRequire("'. $strFile . '",' ,
                'CodeToDiagram::getInstance()->CodeToDiagramInclude("'. $strFile . '",' ,
                'CodeToDiagram::getInstance()->CodeToDiagramIncludeOnce("'. $strFile . '",',
                'CodeToDiagram::getInstance()->CodeToDiagramExit("'. $strFile . '")',
                'CodeToDiagram::getInstance()->CodeToDiagramExit("'. $strFile . '",',
                '"' . $this->getCallerPath() . $strFullFile . '"',
            ),
            $strContentFile
        );
        return $strContentFile;
    }
fixFileName ($ strFileFrom, $ strFile) [protected]
Make the link reference possible
Parameters:
string $strFileFrom
string $strFile
Returns:
string
Definition at line 495 of file CodeToDiagram.class.php.
References $strFileFrom.
Referenced by addFile(), and loadFile().
    {
        $strFileFrom = str_replace( '/', '\\', $strFileFrom );
        $strFile = str_replace( '/', '\\', $strFile );
        $strFilePath = substr( $strFileFrom ,  0 , -(strlen(basename($strFileFrom ) ) ) );
        $strFile = $strFilePath . $strFile;
        return $strFile;
    }
getCallerPath ()
Get the caller path
Returns:
string
Definition at line 336 of file CodeToDiagram.class.php.
Referenced by convertFileContent(), and start().
    {
        return $this->strCallerPath;
    }
getFileFrom ()
Get the file what the execution start from.
Example:
$this->setFileFrom(__FILE__)->getFileFrom() == __FILE__
Returns:
string
Definition at line 284 of file CodeToDiagram.class.php.
Referenced by start().
    {
        return $this->strFileFrom;
    }
getFileName ()
Get the file name of the actual file in code instrumentation
Example:
$this->setFileName("index.php")->getFileName() == "index.php"
Returns:
string
Definition at line 314 of file CodeToDiagram.class.php.
Referenced by save().
    {
        return $this->strFileName;
    }
static getInstance () [static]
Get a singleton instance of the class
Example:
get_class(self::getInstance()) == "CodeToDiagram"
Returns:
CodeToDiagram
Definition at line 207 of file CodeToDiagram.class.php.
Referenced by convertFileContent(), init(), restart(), save(), and start().
    {
        if( self::$objInstance === null )
        {
            self::$objInstance = new CodeToDiagram();
        }
        return self::$objInstance;
    }
getOutputType ()
Get the output type of the diagram
Example:
$this->setOutputType(CodeToDiagram::OUTPUT_TYPE_SCREEN)->getOutputType() == CodeToDiagram::OUTPUT_TYPE_SCREEN
Example:
$this->setOutputType(CodeToDiagram::OUTPUT_TYPE_FILE)->getOutputType() == CodeToDiagram::OUTPUT_TYPE_FILE
Example:
$this->setOutputType(CodeToDiagram::OUTPUT_TYPE_STRING)->getOutputType() == CodeToDiagram::OUTPUT_TYPE_STRING
Example:
$this->setOutputType("something") throws CodeToDiagramException
Returns:
string
Definition at line 172 of file CodeToDiagram.class.php.
Referenced by save().
    {
        return $this->strOutputType;
    }
getPublicPath ()
Get the public path
Returns:
string
Definition at line 358 of file CodeToDiagram.class.php.
Referenced by start().
    {
        return $this->strPublicPath;
    }
getStarted ()
Get if the diagram creation has started
Example:
$this->setStarted(true)->getStarted() == true
Example:
$this->setStarted(false)->getStarted() == false
Assert:
() == false
Returns:
boolean
Definition at line 251 of file CodeToDiagram.class.php.
Referenced by convertFileContent(), init(), save(), and start().
    {
        return $this->booStart;
    }
hasFile ($ strFileFrom, $ strFile) [protected]
Check if the file already was loaded
Parameters:
string $strFileFrom
string $strFile
Returns:
boolean
Definition at line 528 of file CodeToDiagram.class.php.
Referenced by CodeToDiagramIncludeOnce(), and CodeToDiagramRequireOnce().
    {
        return in_array( $strFile ,  $this->arrFiles );
    }
static hasInstance () [static]
Returns if the element has a instance
Example:
self::hasInstance() == false;
Example:
self::getInstance(); self::hasInstance() == true
Returns:
boolean
Definition at line 192 of file CodeToDiagram.class.php.
    {
        return ( self::$objInstance !== null );
    }
static init ($ strFile) [static]
Init the code to diagram
Parameters:
string $strFile
Returns:
CodeToDiagram
Definition at line 478 of file CodeToDiagram.class.php.
References getInstance(), and getStarted().
    {
        if( self::getInstance()->getStarted() == false )
        {
            self::getInstance()->setFileFrom( $strFile );
        }
        return self::getInstance();
    }
loadFile ($ strFileFrom, $ strFile) [protected]
Load some file implement the code instrumentation
Parameters:
string $strFileFrom
string $strFile
Returns:
CodeToDiagram
Definition at line 804 of file CodeToDiagram.class.php.
References $strFileFrom, addFile(), codeInstrumentationFile(), convertFileContent(), fixFileName(), and CorujaFileManipulation::isRelativePath().
Referenced by CodeToDiagramInclude(), and CodeToDiagramRequire().
    {
        if( basename( $strFile ) == 'CodeToDiagram.class.php' )
        {
            return $this;
        }
        $this->addFile( $strFileFrom, $strFile );
        if( CorujaFileManipulation::isRelativePath( $strFile ) )
        {
            $strFullFile = $this->fixFileName( $strFileFrom, $strFile );
        }
        else
        {
            $strFullFile = $strFile;
        }
        if( ! file_exists( $strFullFile ) )
        {
            throw new CodeToDiagramException( "Unable to find file: " . $strFullFile );
        }
        $strContentFile = file_get_contents( $strFullFile );
        $strContentFile = $this->convertFileContent( $strContentFile , $strFile , $strFullFile );
        $this->codeInstrumentationFile( $strFile, $strContentFile );
        return $this;
    }
preloadFile ($ strFileName, $ strContentFile) [protected]
Pre load the file into is's context
Parameters:
string $strFileName
string $strContentFile
Returns:
CodeToDiagram
Definition at line 715 of file CodeToDiagram.class.php.
References $strFileName.
Referenced by codeInstrumentationFile().
    {
        if( self::RUN_IN_FILES )
        {
            $strFileName = $strFileName . "(0).phps";
            file_put_contents( $strFileName , $strContentFile );
            require_once( $strFileName );
            if( self::REMOVE_FILES )
            {
                unlink( $strFileName );
            }
        }
        else
        {
            eval( '?' . '>' . $strContentFile . '' );
        }
        return $this;
    }
restart ()
Restart the informations inside the code instrumentation receiver
Assert:
()
Returns:
CodeToDiagram
Definition at line 394 of file CodeToDiagram.class.php.
References getInstance().
    {
        CodeInstrumentationReceiver::getInstance()->restart();
        return $this;
    }
save ()
Save the actual information from the code instrumentation into the selected output.
Example:
CodeToDiagram::getInstance()->restart(); // output will be a file // CodeToDiagram::getInstance()->setOutputType('file'); // name of the new file // CodeToDiagram::getInstance()->setFileName('myFile.html'); # this code will be saved { $objWolf = new Wolf(); $objWolf->say("i will be back " . date("h:i:s")); CodeToDiagram::getInstance()->save(); # } into the new file
Returns:
string
Definition at line 420 of file CodeToDiagram.class.php.
References $objXmlSequence, getFileName(), getInstance(), getOutputType(), and getStarted().
Referenced by __destruct().
    {
        $strReturn = "";
        if( $this->getStarted() )
        {
                $objXmlSequence = CodeInstrumentationReceiver::getInstance()->getXmlSequence();
            switch( $this->getOutputType() )
            {
                case self::OUTPUT_TYPE_SCREEN:
                {
                        $strDiagram = XmlSequencePrinterDiagram::getInstance()->perform( $objXmlSequence );
                    print $strDiagram;
                    break;
                }
                case self::OUTPUT_TYPE_STRING:
                {
                        $strDiagram = XmlSequencePrinterDiagram::getInstance()->perform( $objXmlSequence );
                        $strReturn = $strDiagram;
                    break;
                }
                case self::OUTPUT_TYPE_FILE:
                {
                        $strDiagram = XmlSequencePrinterDiagram::getInstance()->perform( $objXmlSequence );
                        file_put_contents( $this->getFileName() , $strDiagram );
                    break;
                }
                case self::OUTPUT_TYPE_XML:
                {
                        $strReturn = XmlSequencePrinterXml::getInstance()->perform( $objXmlSequence );
                    break;
                }
                default:
                {
                    throw new CodeToDiagramException( "Invalid output type ({$this->getOutputType()})" );
                    break;
                }
            }
            CodeInstrumentationReceiver::getInstance()->restart();
        }
        return $strReturn;
    }
setCallerPath ($ strCallerPath)
Set the caller path
Parameters:
string $strCallerPath
Returns:
CodeToDiagram me
Definition at line 325 of file CodeToDiagram.class.php.
References $strCallerPath.
Referenced by setCallerPathByFile().
    {
        $this->strCallerPath = $strCallerPath;
        return $this;
    }
setCallerPathByFile ($ strCallerFile)
Set the caller path receiving the caller file
Parameters:
string $strCallerFile
Definition at line 838 of file CodeToDiagram.class.php.
References CorujaFileManipulation::getPathOfFile(), and setCallerPath().
    {
        $this->setCallerPath( CorujaFileManipulation::getPathOfFile( $strCallerFile ) );
    }
setFileFrom ($ strFileFrom)
Set the file what the execution start from. This should be edit with very care
Example:
$this->setFileFrom(__FILE__)->getFileFrom() == __FILE__
Assert:
(__FILE__);
Parameters:
string $strFileFrom
Returns:
CodeToDiagram
Definition at line 268 of file CodeToDiagram.class.php.
References $strFileFrom.
    {
        $this->strFileFrom = $strFileFrom;
        return $this;
    }
setFileName ($ strFileName)
Set the actual file in code instrumentation
Example:
$this->setFileName("index.php")->getFileName() == "index.php"
Parameters:
string $strFileName
Returns:
CodeToDiagram
Definition at line 299 of file CodeToDiagram.class.php.
References $strFileName.
    {
        $this->strFileName = $strFileName;
        return $this;
    }
setOutputType ($ strType)
Set the output type of the diagram
Example:
$this->setOutputType(CodeToDiagram::OUTPUT_TYPE_SCREEN)->getOutputType() == CodeToDiagram::OUTPUT_TYPE_SCREEN
Example:
$this->setOutputType(CodeToDiagram::OUTPUT_TYPE_FILE)->getOutputType() == CodeToDiagram::OUTPUT_TYPE_FILE
Example:
$this->setOutputType(CodeToDiagram::OUTPUT_TYPE_STRING)->getOutputType() == CodeToDiagram::OUTPUT_TYPE_STRING
Example:
$this->setOutputType("something") throws CodeToDiagramException
Assert:
(CodeToDiagram::OUTPUT_TYPE_SCREEN)
Assert:
(CodeToDiagram::OUTPUT_TYPE_FILE)
Assert:
(CodeToDiagram::OUTPUT_TYPE_STRING)
Assert:
("somethingElse") throws CodeToDiagramException
Parameters:
string $strType
Definition at line 129 of file CodeToDiagram.class.php.
References OUTPUT_TYPE_FILE, OUTPUT_TYPE_SCREEN, OUTPUT_TYPE_STRING, and OUTPUT_TYPE_XML.
    {
        switch( $strType )
        {
            case CodeToDiagram::OUTPUT_TYPE_SCREEN:
            case CodeToDiagram::OUTPUT_TYPE_STRING:
            case CodeToDiagram::OUTPUT_TYPE_FILE :
            case CodeToDiagram::OUTPUT_TYPE_XML :
            {
                $this->strOutputType = $strType;
                break;
            }
            default:
            {
                throw new CodeToDiagramException( "Invalid output type. ('" . $strType . "')" );
                break;
            }
        }
        return $this;
    }
setPublicPath ($ strPublicPath)
Set the public path
Parameters:
string $strPublicPath
Returns:
CodeToDiagram me
Definition at line 347 of file CodeToDiagram.class.php.
References $strPublicPath.
    {
        $this->strPublicPath = $strPublicPath;
        return $this;
    }
setStarted ($ booStarted)
Set if the diagram creation has started
Example:
$this->setStarted(true)->getStarted() == true
Example:
$this->setStarted(false)->getStarted() == false
Assert:
(true)
Assert:
(false)
Parameters:
bool $booStarted
Returns:
CodeToDiagram
Definition at line 232 of file CodeToDiagram.class.php.
    {
        $this->booStart = $booStarted;
        return $this;
    }
start ()
Start the log of the execution and restart if already have
Assert:
()
Returns:
CodeToDiagram
Definition at line 370 of file CodeToDiagram.class.php.
References CodeToDiagramRequireOnce(), getCallerPath(), getFileFrom(), getInstance(), getPublicPath(), and getStarted().
    {
        CodeInstrumentationReceiver::getInstance()->setPublicPath( $this->getPublicPath() );
        CodeInstrumentationReceiver::getInstance()->setCallerPath( $this->getCallerPath() );
        if( $this->getStarted() )
        {
            return $this;
        }
        CodeInstrumentationReceiver::getInstance()->restart();
        $this->CodeToDiagramRequireOnce($this->getFileFrom() , $this->getFileFrom() );
        exit();
        // just to safety //
        return $this;
    }
Member Data Documentation
$arrFiles = array() [protected]
Array of files already load
<arrayList>string
Definition at line 21 of file CodeToDiagram.class.php.
$booStart = false [protected]
Flag of control if is the first load
boolean
Definition at line 28 of file CodeToDiagram.class.php.
$objInstance [static, protected]
Singleton of this class
CodeToDiagram
Definition at line 70 of file CodeToDiagram.class.php.
$strCallerPath [protected]
Caller Path of the execution
string
Definition at line 56 of file CodeToDiagram.class.php.
Referenced by setCallerPath().
$strFileFrom = null [protected]
File from the execution start
string
Definition at line 35 of file CodeToDiagram.class.php.
Referenced by addFile(), CodeToDiagramInclude(), CodeToDiagramIncludeOnce(), CodeToDiagramRequire(), CodeToDiagramRequireOnce(), fixFileName(), loadFile(), and setFileFrom().
$strFileName = null [protected]
File of actual load
string
Definition at line 42 of file CodeToDiagram.class.php.
Referenced by codeInstrumentationFile(), preloadFile(), and setFileName().
$strOutputType = self::OUTPUT_TYPE_SCREEN [protected]
Type of output of graph
string
Definition at line 49 of file CodeToDiagram.class.php.
$strPublicPath [protected]
Public Path of the project
string
Definition at line 63 of file CodeToDiagram.class.php.
Referenced by setPublicPath().
const CODE_TO_DIAGRAM_CLASS_PREFIX = "CTD"
Prefix of the code instrumentation classes of the code to diagram
Definition at line 94 of file CodeToDiagram.class.php.
const OUTPUT_TYPE_FILE = "file"
Definition at line 100 of file CodeToDiagram.class.php.
Referenced by setOutputType().
const OUTPUT_TYPE_SCREEN = "screen"
Definition at line 96 of file CodeToDiagram.class.php.
Referenced by setOutputType().
const OUTPUT_TYPE_STRING = "string"
Definition at line 98 of file CodeToDiagram.class.php.
Referenced by setOutputType().
const OUTPUT_TYPE_XML = "xml"
Definition at line 102 of file CodeToDiagram.class.php.
Referenced by setOutputType().
const REMOVE_FILES = true
If the execution happen into files the new file will be destroy just after be executed. This will prevent the existence of garbage files.
boolean
Definition at line 88 of file CodeToDiagram.class.php.
const RUN_IN_FILES = true
Should the code instrumentation run in files If not will run into a eval function
boolean
Definition at line 78 of file CodeToDiagram.class.php.
The documentation for this class was generated from the following file:
components/codeToDiagram/CodeToDiagram.class.php