CodeToDiagram: ExtendedReflectionParameter Class Reference
ExtendedReflectionParameter Class Reference
Public Member Functions
getDeclaringClass ()
getClass ()
getDeclaringFunction ()
Protected Member Functions
createExtendedReflectionClass (ReflectionClass $objOriginalReflectionClass)
createExtendedReflectionMethod (ReflectionMethod $objOriginalReflectionMethod)
createExtendedReflectionFunction (ReflectionFunction $objOriginalReflectionFunction)
Detailed Description
Class what make possible and easy extend reflection parameter
Reflection classes can be a problem because the reflection methods what return objects will return the original reflection object and not the extended version of it. So it is necessary to create methods what convert the original methods to return the extended version of the objects.
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 19 of file ExtendedReflectionParameter.class.php.
Member Function Documentation
createExtendedReflectionClass (ReflectionClass $ objOriginalReflectionClass) [protected]
Convert a reflection class into a extended reflection class
This is the method what should be replaced when this class be extended.
Parameters:
ReflectionClass $objOriginalReflectionClass
Returns:
ExtendedReflectionClass
Reimplemented in CodeInstrumentationParameter, and CodeReflectionParameter.
Definition at line 64 of file ExtendedReflectionParameter.class.php.
Referenced by getClass(), and getDeclaringClass().
        {
                return new ExtendedReflectionClass( $objOriginalReflectionClass->getName() );
        }
createExtendedReflectionFunction (ReflectionFunction $ objOriginalReflectionFunction) [protected]
Convert a reflection function into a extended reflection function
This is the method what should be replaced when this class be extended.
Parameters:
ReflectionFunction $objOriginalReflectionFunction
Returns:
ExtendedReflectionFunction
Reimplemented in CodeInstrumentationParameter, and CodeReflectionParameter.
Definition at line 92 of file ExtendedReflectionParameter.class.php.
Referenced by getDeclaringFunction().
        {
                if( $objOriginalReflectionFunction instanceof ReflectionMethod )
                {
                        return new ExtendedReflectionMethod( $objOriginalReflectionFunction->getName() );
                }
                else
                {
                        return new ExtendedReflectionFunction( $objOriginalReflectionFunction->getName() );
                }
        }
createExtendedReflectionMethod (ReflectionMethod $ objOriginalReflectionMethod) [protected]
Convert a reflection method into a extended reflection method
This is the method what should be replaced when this class be extended.
Parameters:
ReflectionMethod $objOriginalReflectionMethod
Returns:
ExtendedReflectionMethod
Reimplemented in CodeInstrumentationParameter, and CodeReflectionParameter.
Definition at line 78 of file ExtendedReflectionParameter.class.php.
        {
                return new ExtendedReflectionMethod( $this->getName() , $objOriginalReflectionMethod->getName() );
        }
getClass () [final]
Get the class type of the reflected parameter
Returns:
ExtendedReflectionClass
Definition at line 36 of file ExtendedReflectionParameter.class.php.
References createExtendedReflectionClass().
    {
        if( parent::getClass() == null )
        {
                return null;
        }
        return $this->createExtendedReflectionClass( parent::getClass() );
    }
getDeclaringClass () [final]
Get the class owner of the reflected parameter
Returns:
ExtendedReflectionClass
Definition at line 26 of file ExtendedReflectionParameter.class.php.
References createExtendedReflectionClass().
    {
        return $this->createExtendedReflectionClass( parent::getDeclaringClass() );
    }
getDeclaringFunction () [final]
Get the declarion function of the reflected function
Returns:
ExtendedReflectionFunction
Definition at line 50 of file ExtendedReflectionParameter.class.php.
References createExtendedReflectionFunction().
    {
        $objReflectionFunction = $this->createExtendedReflectionFunction( parent::getDeclaringFunction() );
    }
The documentation for this class was generated from the following file:
components/extendedReflection/ExtendedReflectionParameter.class.php