CodeToDiagram: CodeReflectionFunction Class Reference
CodeReflectionFunction Class Reference
Public Member Functions
getCode ()
getCodeContent ()
createFunctionHeaderCode ()
Protected Member Functions
createExtendedReflectionParameter (ReflectionParameter $objReflectionParameter)
createParametersCode ()
createFunctionContentCode ()
Detailed Description
Generate the code definition of some function based into its reflection information
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 14 of file CodeReflectionFunction.class.php.
Member Function Documentation
createExtendedReflectionParameter (ReflectionParameter $ objReflectionParameter) [protected]
Make the reflection parameter link return a code reflection parameter
See also:
ExtendedReflectionFunction::createExtendedReflectionParameter()
Parameters:
ReflectionParameter $objReflectionParameter
Returns:
CodeReflectionParameter
Reimplemented from ExtendedReflectionFunction.
Reimplemented in CodeInstrumentationFunction.
Definition at line 49 of file CodeReflectionFunction.class.php.
        {
                return new CodeReflectionParameter( null , $this->getName() , $objReflectionParameter->getName() );
        }
createFunctionContentCode () [protected]
Creater the function content
Returns:
string
Definition at line 96 of file CodeReflectionFunction.class.php.
References CodeReflectionFile::getCodeInstrFileName().
Referenced by getCode().
        {
                $strCode = "";
                $strFileName = $this->getFileName();
        $objFile = CodeReflectionFile::getCodeInstrFileName( $strFileName );
        $strCode = $objFile->getFileBit( $this->getStartLine() ,  $this->getEndLine() );
                $strCode = trim( $strCode );
                // remove the { }
                if( $strCode[0] == "{" )
                {
                        $strCode = substr( $strCode , 1 , -1);
                }
                return $strCode;
        }
createFunctionHeaderCode ()
Create the function header code
Definition at line 81 of file CodeReflectionFunction.class.php.
References createParametersCode(), and CorujaStringManipulation::retab().
Referenced by getCode().
        {
                $strCode = $this->getDocComment();
                $strCode .= " function ";
                $strCode .= $this->getName();
                $strCode .= $this->createParametersCode();
                return CorujaStringManipulation::retab( $strCode , 1 );
        }
createParametersCode () [protected]
Get the code of the parameters definition
Returns:
string
Definition at line 59 of file CodeReflectionFunction.class.php.
References ExtendedReflectionFunction::getParameters().
Referenced by createFunctionHeaderCode().
        {
                $strCode = "";
                $arrParameters = $this->getParameters();
                $arrParametersName = array();
                foreach(  $arrParameters as $objParameter )
                {
                        /*@var $objParameter CodeReflectionParameter */
                        $arrParametersName[] = $objParameter->getCode();
                }
                $strCode .= "(";
                $strCode .= implode( ", " , $arrParametersName);
                $strCode .= ")";
                return $strCode;
        }
getCode ()
Create the code of the function based into reflection's information
Returns:
string
Definition at line 21 of file CodeReflectionFunction.class.php.
References createFunctionContentCode(), and createFunctionHeaderCode().
        {
                $strCode = "";
                $strCode .= $this->createFunctionHeaderCode();
                $strCode .= "{";
                $strCode .= $this->createFunctionContentCode();
                $strCode .= "}\n";
                return $strCode;
        }
getCodeContent ()
Get the code content
Returns:
string
Definition at line 37 of file CodeReflectionFunction.class.php.
    {
        return $this->createMethodContentCode();
    }
The documentation for this class was generated from the following file:
components/codeReflection/CodeReflectionFunction.class.php