CodeToDiagram: CodeReflectionFile Class Reference
CodeReflectionFile Class Reference
Public Member Functions
__construct ($strFileName, $strFileContent="", $boolRealFile=true)
setFileName ($strFileName)
getFileName ()
setFileContent ($strFileContent)
getFileContent ()
getArrFileContent ()
getFileBit ($intLineStart, $intLineEnds)
isRealFile ()
Static Public Member Functions
static getCodeInstrFileName ($strFileName)
Protected Attributes
$strFileName
$arrFileContent
$boolRealFile
Static Protected Attributes
static $arrInstances = array()
Detailed Description
Code Reflection File it is a class with the prupose to make possible abstract the diference between code run into real files and code run into eval commands.
In this mode this class keep the alias fake name of the alias content and the file content, this information can be access by others classes what will be able to interaction with the fake file.
You can get a streck of code of the memory file or the real file using the same method send the first line and last line of the bit of code what you want to receive.
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 21 of file CodeReflectionFile.class.php.
Constructor & Destructor Documentation
__construct ($ strFileName, $ strFileContent = "", $ boolRealFile = true)
Create the Code Reflection File
See also:
CodeReflectionFile::$arrInstances
CodeReflectionFile::setFileName(string)
CodeReflectionFile::setFileContent(string)
Parameters:
string $strFileName file name
string $strFileContent file content
boolean $boolRealFile if is a real file or not
Definition at line 85 of file CodeReflectionFile.class.php.
References $boolRealFile, $strFileName, setFileContent(), and setFileName().
    {
        $this->setFileName( $strFileName);
        $this->setFileContent( $strFileContent );
        $this->boolRealFile = (bool)$boolRealFile;
        self::$arrInstances[ $strFileName ] = $this;
    }
Member Function Documentation
getArrFileContent ()
Get the array of lines with the code file content
Set the code file content and return itselft.
See also:
CodeReflectionFile->arrFileContent
CodeReflectionFile::setFileContent(string)
CodeReflectionFile::getFileContent()
Returns:
string[] array of file content
Definition at line 158 of file CodeReflectionFile.class.php.
    {
        return $this->arrFileContent;
    }
static getCodeInstrFileName ($ strFileName) [static]
Get The File by Name
Search into all object files saved and return that one have the searched name
See also:
CodeReflectionFile->arrInstances
Parameters:
string $strFileName
Returns:
CodeReflectionFile
Definition at line 63 of file CodeReflectionFile.class.php.
References $strFileName.
Referenced by CodeReflectionFunction::createFunctionContentCode(), CodeReflectionMethod::createMethodContentCode(), and CodeInstrumentationMethod::createMethodContentCode().
    {
        if( array_key_exists( $strFileName , self::$arrInstances ) )
        {
            return      self::$arrInstances[ $strFileName ];
        }
        else
        {
            return new CodeReflectionFile( $strFileName );
        }
    }
getFileBit ($ intLineStart, $ intLineEnds)
Get a slice, a streck, a bit of the content of the file receiving the first and last line of the slice wish.
See also:
CodeReflectionFile::setFileContent(string)
CodeReflectionFile->arrFileContent
CodeReflectionFile->arrFileContent
Parameters:
integer $intLineStart first line of the content
integer $intLineEnds last line of the content
Returns:
string code content
Definition at line 174 of file CodeReflectionFile.class.php.
References CorujaArrayManipulation::getArrayField(), getFileName(), isRealFile(), and setFileContent().
    {
        $strFileBit = "";
        if( $this->isRealFile() )
        {
            $this->setFileContent( $this->getFileName() );
        }
        for( $intLine = $intLineStart ; $intLine < $intLineEnds ; ++$intLine )
        {
            $strFileBit .= CorujaArrayManipulation::getArrayField( $this->arrFileContent ,$intLine , "") . "\n";
        }
        return $strFileBit;
    }
getFileContent ()
Get the file content
See also:
CodeReflectionFile->arrFileContent
CodeReflectionFile::setFileContent(string)
Returns:
string file content
Definition at line 142 of file CodeReflectionFile.class.php.
    {
        return implode( "\n" , $this->arrFileContent );
    }
getFileName ()
Get the file name
See also:
CodeReflectionFile::setFileName(string)
CodeReflectionFile->strFileName
Returns:
string file name
Definition at line 114 of file CodeReflectionFile.class.php.
Referenced by getFileBit().
    {
        return $this->strFileName;
    }
isRealFile ()
Returns if the file it is a real file
See also:
CodeReflectionFile->boolRealFile
Returns:
boolean true if is a real file false if not
Definition at line 196 of file CodeReflectionFile.class.php.
Referenced by getFileBit().
    {
        return $this->boolRealFile;
    }
setFileContent ($ strFileContent)
Set the code Reflection file content
Set the code Reflection file content and return itselft.
See also:
CodeReflectionFile->arrFileContent
Parameters:
string $strFileContent file content
Returns:
CodeReflectionFile me
Definition at line 129 of file CodeReflectionFile.class.php.
Referenced by __construct(), and getFileBit().
    {
        $this->arrFileContent = explode( "\n" , (string)$strFileContent );
        return $this;
    }
setFileName ($ strFileName)
Set the file name
See also:
CodeReflectionFile::getFileName()
CodeReflectionFile->strFileName
Parameters:
string $strFileName file name
Returns:
CodeReflectionFile me
Definition at line 101 of file CodeReflectionFile.class.php.
References $strFileName.
Referenced by __construct().
    {
        $this->strFileName = (string)$strFileName;
        return $this;
    }
Member Data Documentation
$arrFileContent [protected]
File Content
string
Definition at line 42 of file CodeReflectionFile.class.php.
$arrInstances = array() [static, protected]
array of all instances of CodeReflectionFile using the name as key
CodeReflectionFile[]
Definition at line 28 of file CodeReflectionFile.class.php.
$boolRealFile [protected]
Flag if the file it is a real file true if is a real file false if is a not real file
boolean
Definition at line 51 of file CodeReflectionFile.class.php.
Referenced by __construct().
$strFileName [protected]
File Name
string
Definition at line 35 of file CodeReflectionFile.class.php.
Referenced by __construct(), getCodeInstrFileName(), and setFileName().
The documentation for this class was generated from the following file:
components/codeReflection/CodeReflectionFile.class.php