CodeToDiagram: ExampleCodeReflecion Class Reference
ExampleCodeReflecion Class Reference
Public Member Functions
doSomethingCool ($strName="hi", exampleSecond $obSecond=null, exampleSecond $objLastOne=null)
hardWork ()
Static Protected Attributes
static $arrParadas = array()
Static Private Member Functions
static doNothing ()
Private Attributes
$strName
Detailed Description
Definition at line 15 of file test1.php.
Member Function Documentation
static doNothing () [static, private]
Definition at line 38 of file test1.php.
Referenced by doSomethingCool().
        {
                // empty...
        }
doSomethingCool ($ strName = "hi", exampleSecond $ obSecond = null, exampleSecond $ objLastOne = null) [final]
Will do something cool
Returns:
string
Definition at line 31 of file test1.php.
References $strName, and doNothing().
Referenced by hardWork().
        {
                $this->strName = $strName;
                print "i change the name to " . $this->strName;
                $this->doNothing();
        }
hardWork ()
Definition at line 43 of file test1.php.
References doSomethingCool().
        {
                for( $i = 0 ; $i < 20 ; $i++ )
                {
                        $this->doSomethingCool( $i );
                }
        }
Member Data Documentation
$arrParadas = array() [static, protected]
Definition at line 24 of file test1.php.
$strName [private]
else
string
Definition at line 22 of file test1.php.
Referenced by doSomethingCool().
The documentation for this class was generated from the following file:
components/codeReflection/example/test1.php