CodeToDiagram: CorujaStringManipulationTest Class Reference
CorujaStringManipulationTest Class Reference
Public Member Functions
testStrToBool ()
testStrToBool2 ()
testStrToBool3 ()
testStrToBool4 ()
testStrToBool5 ()
testStrToBool6 ()
testStrToBool7 ()
testStrToBool8 ()
testStrToBool9 ()
testStrToBool10 ()
testStrToBool11 ()
testStrToBool12 ()
testForceInt ()
testForceInt2 ()
testForceInt3 ()
testForceInt4 ()
testForceInt5 ()
testForceInt6 ()
testForceInt7 ()
testForceInt8 ()
testForceInt9 ()
testForceInt10 ()
testForceInt11 ()
testForceInt12 ()
testForceInt13 ()
testForceInt14 ()
testCamelCaseToUnderlineCase ()
testCamelCaseToUnderlineCase2 ()
testCamelCaseToUnderlineCase3 ()
testCamelCaseToUnderlineCase4 ()
testCamelCaseToUnderlineCase5 ()
testCamelCaseToUnderlineCase6 ()
testCamelCaseToUnderlineCase7 ()
testCamelCaseToUnderlineCase8 ()
testCamelCaseToUnderlineCase9 ()
testCamelCaseToUnderlineCase10 ()
Protected Member Functions
setUp ()
tearDown ()
Protected Attributes
$object
Detailed Description
Test class for CorujaStringManipulation. Generated by PHPUnit on 2008-10-28 at 14:52:27.
Definition at line 10 of file CorujaStringManipulationTest.php.
Member Function Documentation
setUp () [protected]
Sets up the fixture, for example, opens a network connection. This method is called before a test is executed.
protected
Definition at line 24 of file CorujaStringManipulationTest.php.
    {
        $this->object = new CorujaStringManipulation;
    }
tearDown () [protected]
Tears down the fixture, for example, closes a network connection. This method is called after a test is executed.
protected
Definition at line 35 of file CorujaStringManipulationTest.php.
    {
    }
testCamelCaseToUnderlineCase ()
Generated from
Assert:
("test") == "TEST".
Definition at line 301 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        $this->assertEquals(
          "TEST",
          CorujaStringManipulation::camelCaseToUnderlineCase("test")
        );
    }
testCamelCaseToUnderlineCase10 ()
Generated from
Assert:
(false) throws InvalidArgumentException. InvalidArgumentException
Definition at line 393 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        CorujaStringManipulation::camelCaseToUnderlineCase(false);
    }
testCamelCaseToUnderlineCase2 ()
Generated from
Assert:
("somethingCool") == "SOMETHING_COOL".
Definition at line 312 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        $this->assertEquals(
          "SOMETHING_COOL",
          CorujaStringManipulation::camelCaseToUnderlineCase("somethingCool")
        );
    }
testCamelCaseToUnderlineCase3 ()
Generated from
Assert:
("") == "".
Definition at line 323 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        $this->assertEquals(
          "",
          CorujaStringManipulation::camelCaseToUnderlineCase("")
        );
    }
testCamelCaseToUnderlineCase4 ()
Generated from
Assert:
("1something2Cool3") == "1SOMETHING2_COOL3".
Definition at line 334 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        $this->assertEquals(
          "1SOMETHING2_COOL3",
          CorujaStringManipulation::camelCaseToUnderlineCase("1something2Cool3")
        );
    }
testCamelCaseToUnderlineCase5 ()
Generated from
Assert:
("111something2222Cool333") == "111SOMETHING2222_COOL333".
Definition at line 345 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        $this->assertEquals(
          "111SOMETHING2222_COOL333",
          CorujaStringManipulation::camelCaseToUnderlineCase("111something2222Cool333")
        );
    }
testCamelCaseToUnderlineCase6 ()
Generated from
Assert:
(null) throws InvalidArgumentException. InvalidArgumentException
Definition at line 357 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        CorujaStringManipulation::camelCaseToUnderlineCase(null);
    }
testCamelCaseToUnderlineCase7 ()
Generated from
Assert:
(123) throws InvalidArgumentException. InvalidArgumentException
Definition at line 366 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        CorujaStringManipulation::camelCaseToUnderlineCase(123);
    }
testCamelCaseToUnderlineCase8 ()
Generated from
Assert:
(array()) throws InvalidArgumentException. InvalidArgumentException
Definition at line 375 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        CorujaStringManipulation::camelCaseToUnderlineCase(array());
    }
testCamelCaseToUnderlineCase9 ()
Generated from
Assert:
(new stdClass()) throws InvalidArgumentException. InvalidArgumentException
Definition at line 384 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::camelCaseToUnderlineCase().
    {
        CorujaStringManipulation::camelCaseToUnderlineCase(new stdClass());
    }
testForceInt ()
Generated from
Assert:
("a1b2c3d4") == 1234.
Definition at line 157 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        $this->assertEquals(
          1234,
          CorujaStringManipulation::forceInt("a1b2c3d4")
        );
    }
testForceInt10 ()
Generated from
Assert:
(null) throws InvalidArgumentException. InvalidArgumentException
Definition at line 257 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        CorujaStringManipulation::forceInt(null);
    }
testForceInt11 ()
Generated from
Assert:
(123) throws InvalidArgumentException. InvalidArgumentException
Definition at line 266 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        CorujaStringManipulation::forceInt(123);
    }
testForceInt12 ()
Generated from
Assert:
(array()) throws InvalidArgumentException. InvalidArgumentException
Definition at line 275 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        CorujaStringManipulation::forceInt(array());
    }
testForceInt13 ()
Generated from
Assert:
(new stdClass()) throws InvalidArgumentException. InvalidArgumentException
Definition at line 284 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        CorujaStringManipulation::forceInt(new stdClass());
    }
testForceInt14 ()
Generated from
Assert:
(false) throws InvalidArgumentException. InvalidArgumentException
Definition at line 293 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        CorujaStringManipulation::forceInt(false);
    }
testForceInt2 ()
Generated from
Assert:
("") == 0.
Definition at line 168 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        $this->assertEquals(
          0,
          CorujaStringManipulation::forceInt("")
        );
    }
testForceInt3 ()
Generated from
Assert:
("a0a") == 0.
Definition at line 179 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        $this->assertEquals(
          0,
          CorujaStringManipulation::forceInt("a0a")
        );
    }
testForceInt4 ()
Generated from
Assert:
("001") == 1.
Definition at line 190 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        $this->assertEquals(
          1,
          CorujaStringManipulation::forceInt("001")
        );
    }
testForceInt5 ()
Generated from
Assert:
("abc") == 0.
Definition at line 201 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        $this->assertEquals(
          0,
          CorujaStringManipulation::forceInt("abc")
        );
    }
testForceInt6 ()
Generated from
Assert:
("a-10") == 10.
Definition at line 212 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        $this->assertEquals(
          10,
          CorujaStringManipulation::forceInt("a-10")
        );
    }
testForceInt7 ()
Generated from
Assert:
("-10") == -10.
Definition at line 223 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        $this->assertEquals(
          -10,
          CorujaStringManipulation::forceInt("-10")
        );
    }
testForceInt8 ()
Generated from
Assert:
("--10") == -10.
Definition at line 234 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        $this->assertEquals(
          -10,
          CorujaStringManipulation::forceInt("--10")
        );
    }
testForceInt9 ()
Generated from
Assert:
("-a-b-1-0-") == -10.
Definition at line 245 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::forceInt().
    {
        $this->assertEquals(
          -10,
          CorujaStringManipulation::forceInt("-a-b-1-0-")
        );
    }
testStrToBool ()
Generated from
Assert:
("") == false.
Definition at line 42 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        $this->assertFalse(
          CorujaStringManipulation::strToBool("")
        );
    }
testStrToBool10 ()
Generated from
Assert:
(array()) throws InvalidArgumentException. InvalidArgumentException
Definition at line 131 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        CorujaStringManipulation::strToBool(array());
    }
testStrToBool11 ()
Generated from
Assert:
(new stdClass()) throws InvalidArgumentException. InvalidArgumentException
Definition at line 140 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        CorujaStringManipulation::strToBool(new stdClass());
    }
testStrToBool12 ()
Generated from
Assert:
(false) throws InvalidArgumentException. InvalidArgumentException
Definition at line 149 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        CorujaStringManipulation::strToBool(false);
    }
testStrToBool2 ()
Generated from
Assert:
("false") == false.
Definition at line 52 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        $this->assertFalse(
          CorujaStringManipulation::strToBool("false")
        );
    }
testStrToBool3 ()
Generated from
Assert:
("FaLsE") == false.
Definition at line 62 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        $this->assertFalse(
          CorujaStringManipulation::strToBool("FaLsE")
        );
    }
testStrToBool4 ()
Generated from
Assert:
("0") == false.
Definition at line 72 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        $this->assertFalse(
          CorujaStringManipulation::strToBool("0")
        );
    }
testStrToBool5 ()
Generated from
Assert:
("a0a") == true.
Definition at line 82 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        $this->assertTrue(
          CorujaStringManipulation::strToBool("a0a")
        );
    }
testStrToBool6 ()
Generated from
Assert:
("true") == true.
Definition at line 92 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        $this->assertTrue(
          CorujaStringManipulation::strToBool("true")
        );
    }
testStrToBool7 ()
Generated from
Assert:
("1") == true.
Definition at line 102 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        $this->assertTrue(
          CorujaStringManipulation::strToBool("1")
        );
    }
testStrToBool8 ()
Generated from
Assert:
(null) throws InvalidArgumentException. InvalidArgumentException
Definition at line 113 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        CorujaStringManipulation::strToBool(null);
    }
testStrToBool9 ()
Generated from
Assert:
(123) throws InvalidArgumentException. InvalidArgumentException
Definition at line 122 of file CorujaStringManipulationTest.php.
References CorujaStringManipulation::strToBool().
    {
        CorujaStringManipulation::strToBool(123);
    }
Member Data Documentation
$object [protected]
CorujaStringManipulation protected
Definition at line 16 of file CorujaStringManipulationTest.php.
The documentation for this class was generated from the following file:
components/library/test/CorujaStringManipulationTest.php