CodeToDiagram: XmlSequencePrinterDiagram Class Reference
XmlSequencePrinterDiagram Class Reference
Public Member Functions
perform (XmlSequence $objXmlSequence)
setZoom ($intZoom)
getZoom ()
show ()
showValues (XmlSequenceMessage $objXmlMessage)
Static Public Member Functions
static getInstance ()
Protected Member Functions
showHeaders ()
showFooter ()
showActors ()
showMessages ()
Protected Attributes
$objXmlSequence
$intMessageWidth = 300
$intActorHeaderWidth = 100
$intActorBarWidth = 10
$intFont = 13
$intZoom = 100
Static Protected Attributes
static $objInstance
Detailed Description
Generate a html diagram of the xml sequence object
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 13 of file XmlSequencePrinterDiagram.class.php.
Member Function Documentation
static getInstance () [static]
Return the singleton of the XmlSequencePrinterDiagram
See also:
XmlSequencePrinterInterface::getInstance
Returns:
XmlSequencePrinterDiagram
Implements XmlSequencePrinterInterface.
Definition at line 73 of file XmlSequencePrinterDiagram.class.php.
        {
                if( self::$objInstance == null )
                {
                        self::$objInstance = new XmlSequencePrinterDiagram();
                }
                return self::$objInstance;
        }
getZoom ()
Get the zoom of the diagram
Returns:
integer
Definition at line 113 of file XmlSequencePrinterDiagram.class.php.
    {
        return $this->intZoom;
    }
perform (XmlSequence $ objXmlSequence)
Perfom the print process
See also:
XmlSequencePrinterInterface::perform(XmlSequence)
Parameters:
XmlSequence $objXmlSequence
Returns:
mixer
Implements XmlSequencePrinterInterface.
Definition at line 89 of file XmlSequencePrinterDiagram.class.php.
References show().
        {
                $this->objXmlSequence = $objXmlSequence;
                return $this->show();
        }
setZoom ($ intZoom)
Set the zoom of the diagram
Parameters:
integer $intZoom
Returns:
XmlSequence me
Definition at line 102 of file XmlSequencePrinterDiagram.class.php.
References $intZoom.
    {
        $this->intZoom = $intZoom;
        return $this;
    }
show ()
Definition at line 118 of file XmlSequencePrinterDiagram.class.php.
References showActors(), showFooter(), showHeaders(), and showMessages().
Referenced by perform().
    {
        $strHtml = '';
        $strHtml .= $this->showHeaders();
        $strHtml .= $this->showActors();
        $strHtml .= $this->showMessages();
        $strHtml .= $this->showFooter();
        return $strHtml;
    }
showActors () [protected]
Create and return the string of the actors of the html sequence diagram
Returns:
string
$objActor XmlSequenceActor
Definition at line 202 of file XmlSequencePrinterDiagram.class.php.
Referenced by show().
    {
        $strHtmlActors = '';
        $strHtmlActors .=
<<<HTML
    <div class="line head">
HTML;
        $arrActors = $this->objXmlSequence->getActors();
        foreach( $arrActors as $objActor )
        {
            $arrActorName = explode( ":" , $objActor->getName() );
            $strClass = array_pop( $arrActorName );
            array_push( $arrActorName , '<strong>' . $strClass . '</strong>' );
            $strActorName = implode( " : " , $arrActorName );
            $strHtmlActors .=
<<<HTML
            <div class="row">
                <div class="message">
                    <span>&nbsp;</span>
                </div>
            </div>
            <div class="actor {$objActor->getType()}">
                <div class="name">
                    <span title="{$objActor->getName()}">{$strActorName}</span>
                </div>
            </div>
HTML;
         }
        $strHtmlActors .=
<<<HTML
    </div>
HTML;
         return $strHtmlActors;
    }
showFooter () [protected]
Create and return the string of the footer of the html sequence diagram
Returns:
string
Definition at line 192 of file XmlSequencePrinterDiagram.class.php.
Referenced by show().
    {
        return ' </div> ';
    }
showHeaders () [protected]
Create and return the string of the header of the html sequence diagram
Returns:
string
Definition at line 133 of file XmlSequencePrinterDiagram.class.php.
References $intFont, $intMessageWidth, and CorujaFileManipulation::getRelativePath().
Referenced by show().
    {
        if( $this->objXmlSequence->getCallerPath() != null and $this->objXmlSequence->getPublicPath() != null )
        {
            $strPublicPath = CorujaFileManipulation::getRelativePath( $this->objXmlSequence->getCallerPath(), $this->objXmlSequence->getPublicPath() );
        }
        elseif( $this->objXmlSequence->getCallerPath() == null and $this->objXmlSequence->getPublicPath() != null )
        {
            $strPublicPath = $this->objXmlSequence->getPublicPath();
        }
        else
        {
            $strPublicPath = "./";
        }
        $intQtdActors = sizeof( $this->objXmlSequence->getActors() );
        $intQtdMessages = $intQtdActors + 1;
        $intBodyWidth =
            ( $this->intMessageWidth * $intQtdMessages * $this->intZoom / 100 )
            +
            ( 100 * $intQtdActors * $this->intZoom / 100 );
        $intFont = ( $this->intFont + round( $this->intFont * $this->intZoom / 100 ) ) / 2;
        $intMessageWidth = round( $this->intMessageWidth * $this->intZoom / 100 );
        $intMessageHeight = max( 40 ,  round( 40 * $this->intZoom / 100 ) );
        $strHtmlHeaders =
<<<HTML
            <style>
                @import "{$strPublicPath}css/sequenceStyle.css";
                .sequenceDiagram
                {
                    width: {$intBodyWidth}px;
                }
                .row
                {
                    height:{$intMessageHeight}px;
                    width: {$intMessageWidth}px;
                    font-size: {$intFont};
                }
                .row span
                {
                    height: 50%;
                }
                .actor .name
                {
                    height:{$intMessageHeight}px;
                }
            </style>
            <div class='sequenceDiagram'>
HTML;
        return $strHtmlHeaders;
    }
showMessages () [protected]
Create and return the string of the messages into the html sequence diagram
Returns:
string
$objMessage XmlSequenceMessage
$objActorNext XmlSequenceActor
$objActorActual XmlSequenceActor
Definition at line 256 of file XmlSequencePrinterDiagram.class.php.
References showValues().
Referenced by show().
    {
        $strHtmlMessages = '';
        $arrMessages = $this->objXmlSequence->getMessages();
        foreach( $arrMessages as $intKey => $objMessage )
        {
            $intPos = $intKey + 1;
            if( $objMessage->isReverse() )
            {
                $intStart = $objMessage->getActorTo()->getId();
                $intEnd = $objMessage->getActorFrom()->getId();
            }
            else
            {
                $intEnd = $objMessage->getActorTo()->getId();
                $intStart = $objMessage->getActorFrom()->getId();
            }
$strHtmlMessages .=
<<<HTML
            <div class="line body">
                  <div class="row " >
                    <div class="message ">
                      <span>&nbsp;</span>
                    </div>
                  </div>
HTML;
            $arrActors = $this->objXmlSequence->getActors();
            $strReverse = $objMessage->isReverse() ? 'reverse' : 'regular';
            $strLarge = $objMessage->isLarge() ? 'large' : 'short';
            $strRecursive = $objMessage->isRecursive() ? 'recursive' : 'line';
            while( $objActorActual = array_shift( $arrActors ) )
            {
                $objActorNext = current( $arrActors );
                if( $objActorNext == false )
                {
                    $objActorNext = new XmlSequenceActor();
                    $objActorNext->setId( $objActorActual->getId() + 1 );
                }
               if( $objActorActual->getId() < $intStart )
               {
                   // before line //
                    $strHtmlMessages .=
<<<HTML
                  <div class="actor">
                    <div class="name">
                      <span title="{$objActorActual->getName()}">&nbsp;</span>
                    </div>
                  </div>
                  <div class="row">
                    <div class="message">
                      <span>&nbsp;</span>
                    </div>
                  </div>
HTML;
               }
               elseif( $objActorActual->getId() == $intStart )
               {
                   // start line //
                    $strHtmlMessages .=
<<<HTML
                  <div class="actor start">
                    <div class="name">
                      <span title="{$objActorActual->getName()}">&nbsp;</span>
                    </div>
                  </div>
                  <div class="row {$objMessage->getType()} {$strReverse} {$strLarge} {$strRecursive} start ">
                    <div class="message ">
                      <span><strong>{$intPos}</strong>. {$objMessage->getText()}</span>
                    {$this->showValues( $objMessage )}
                    </div>
                  </div>
HTML;
               }
               elseif( ( $objActorActual->getId() > $intStart ) and ($objActorNext->getId() < $intEnd ) )
               {
                   // inside line //
                    $strHtmlMessages .=
<<<HTML
                  <div class="actor middle {$objMessage->getType()}">
                    <div class="name">
                      <span title="{$objActorActual->getName()}">&nbsp;</span>
                    </div>
                  </div>
                  <div class="row {$objMessage->getType()} {$strReverse} {$strLarge} middle ">
                    <div class="message">
                      <span>&nbsp;</span>
                    </div>
                  </div>
HTML;
               }
               elseif( $objActorNext->getId() == $intEnd )
               {
                    $strHtmlMessages .=
<<<HTML
                  <div class="actor end {$objMessage->getType()}">
                    <div class="name">
                      <span title="{$objActorActual->getName()}">&nbsp;</span>
                    </div>
                  </div>
                  <div class="row {$objMessage->getType()} {$strReverse}  end ">
                    <div class="message ">
                      <span>&nbsp;</span>
                    </div>
                  </div>
HTML;
               }
               elseif( $objActorNext->getId() > $intEnd )
               {
                   $intDif = $objActorNext->getId() - $intEnd;
                    $strHtmlMessages .=
<<<HTML
                  <div class="actor after{$intDif}">
                    <div class="name">
                      <span title="{$objActorActual->getName()}">&nbsp;</span>
                    </div>
                  </div>
                  <div class="row">
                    <div class="message">
                      <span>&nbsp;</span>
                    </div>
                  </div>
HTML;
               }
               else
               {
                   $strMessage = '';
                   $strMessage .= ' Invalid Id ' . "\n" ;
                   $strMessage .= ' Actual Actor ' . $objActorActual->getId() ;
                   $strMessage .= ' Next Actor ' . $objActorNext->getId() ;
                   $strMessage .= ' Message Start ' . $intStart ;
                   $strMessage .= ' Message End' . $intEnd ;
                   throw new Exception( $strMessage );
               }
            }
        $strHtmlMessages .=
<<<HTML
            </div>
HTML;
        }
        return $strHtmlMessages;
    }
showValues (XmlSequenceMessage $ objXmlMessage)
Create and return the html of some values of some messages into the html sequence diagram
Parameters:
XmlSequenceMessage $objXmlMessage
Returns:
string
Definition at line 430 of file XmlSequencePrinterDiagram.class.php.
References XmlSequenceMessage::getValues().
Referenced by showMessages().
    {
        $arrValues = $objXmlMessage->getValues();
        if( sizeof( $arrValues ) > 0 )
        {
            $strHtml = '<div class="parameters">';
            $strHtml .= '<ul>' . "\n";
            foreach( $arrValues as $objValue )
            {
                $strHtml .= '<li>' . "\n";
                $strHtml .= '   <strong>' . $objValue->getName() . '</strong>' . "\n";
                $strHtml .= '   ' . $objValue->getValue() . ' ' . "\n";
                $strHtml .= '</li>' . "\n";
            }
            $strHtml .= '</ul></div>' . "\n";
        }
        else
        {
            $strHtml = '';
        }
        return $strHtml;
    }
Member Data Documentation
$intActorBarWidth = 10 [protected]
width (in pixels) for each actor bar
integer
Definition at line 51 of file XmlSequencePrinterDiagram.class.php.
$intActorHeaderWidth = 100 [protected]
width (in pixels) for each actor header
integer
Definition at line 44 of file XmlSequencePrinterDiagram.class.php.
$intFont = 13 [protected]
size (in pixels) of text font
integer
Definition at line 58 of file XmlSequencePrinterDiagram.class.php.
Referenced by showHeaders().
$intMessageWidth = 300 [protected]
width (in pixels) for each message
integer
Definition at line 37 of file XmlSequencePrinterDiagram.class.php.
Referenced by showHeaders().
$intZoom = 100 [protected]
zoom in % of the diagram
integer
Definition at line 65 of file XmlSequencePrinterDiagram.class.php.
Referenced by setZoom().
$objInstance [static, protected]
Singleton of the XmlSequencePrinterDiagram
See also:
XmlSequencePrinterInterface::$objInstance
XmlSequencePrinterDiagram
Definition at line 29 of file XmlSequencePrinterDiagram.class.php.
$objXmlSequence [protected]
xml sequence object what will be print
See also:
XmlSequencePrinterInterface->objXmlSequence
XmlSequence
Definition at line 21 of file XmlSequencePrinterDiagram.class.php.
The documentation for this class was generated from the following file:
components/xmlSequence/XmlSequencePrinterDiagram.class.php