CodeToDiagram: ExtendedReflectionClass Class Reference
ExtendedReflectionClass Class Reference
Public Member Functions
getParentClass ()
getInterfaces ()
getProperties ($filter=-1)
getProperty ($strName)
getMethods ($filter=-1)
getMethod ($strMethodName)
Protected Member Functions
createExtendedReflectionClass (ReflectionClass $objOriginalReflectionClass)
createExtendedReflectionProperty (ReflectionProperty $objOriginalReflectionProperty)
createExtendedReflectionMethod (ReflectionMethod $objOriginalReflectionMethod)
Detailed Description
Class what make possible and easy extends reflection classes
Reflection classes can be a problem because the reflection methods what return objects will return the original reflection object and not the extended version of it. So it is necessary to create methods what convert the original methods to return the extended version of the objects.
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 20 of file ExtendedReflectionClass.class.php.
Member Function Documentation
createExtendedReflectionClass (ReflectionClass $ objOriginalReflectionClass) [protected]
Convert a reflection class into a extended reflection class
This is the method what should be replaced when this class be extended.
Parameters:
ReflectionClass $objOriginalReflectionClass
Returns:
ExtendedReflectionClass
Reimplemented in CodeInstrumentationClass, and CodeReflectionClass.
Definition at line 128 of file ExtendedReflectionClass.class.php.
Referenced by getInterfaces(), and getParentClass().
        {
                return new ExtendedReflectionClass( $objOriginalReflectionClass->getName() );
        }
createExtendedReflectionMethod (ReflectionMethod $ objOriginalReflectionMethod) [protected]
Convert a reflection method into a extended reflection method
This is the method what should be replaced when this class be extended.
Parameters:
ReflectionMethod $objOriginalReflectionMethod
Returns:
ExtendedReflectionMethod
Reimplemented in CodeInstrumentationClass, and CodeReflectionClass.
Definition at line 156 of file ExtendedReflectionClass.class.php.
Referenced by getMethod(), and getMethods().
        {
                return new ExtendedReflectionMethod( $this->getName() , $objOriginalReflectionMethod->getName() );
        }
createExtendedReflectionProperty (ReflectionProperty $ objOriginalReflectionProperty) [protected]
Convert a reflection property into a extended reflection property
This is the method what should be replaced when this class be extended.
Parameters:
ReflectionProperty $objOriginalReflectionProperty
Returns:
ExtendedReflectionProperty
Reimplemented in CodeInstrumentationClass, and CodeReflectionClass.
Definition at line 142 of file ExtendedReflectionClass.class.php.
Referenced by getProperties(), and getProperty().
        {
                return new ExtendedReflectionProperty( $this->getName() , $objOriginalReflectionProperty->getName() );
        }
getInterfaces () [final]
Get the collection of the reflection class of all the interfaces implemented by the reflected class
Returns:
ExtendedReflectionClass[]
Definition at line 47 of file ExtendedReflectionClass.class.php.
References createExtendedReflectionClass().
Referenced by CodeReflectionClass::createClassDefinitionCode().
        {
                $arrOriginalInterfaces = parent::getInterfaces();
                $arrExtendedInterfaces = array();
                foreach( $arrOriginalInterfaces as $objInterface )
                {
                        /*@var $objInterface ReflectionClass */
                        $arrExtendedInterfaces[] = $this->createExtendedReflectionClass( $objInterface );
                }
                return $arrExtendedInterfaces;
        }
getMethod ($ strMethodName) [final]
Return the reflection of some method of the class
Parameters:
$strMethodName
Returns:
ExtendedReflectionMethod
Definition at line 114 of file ExtendedReflectionClass.class.php.
References createExtendedReflectionMethod().
    {
        return $this->createExtendedReflectionMethod( parent::getMethod( $strMethodName ) );
    }
getMethods ($ filter = -1) [final]
Get the collection of the reflected methods
Parameters:
$filter
Returns:
ReflectionMethod[]
Definition at line 96 of file ExtendedReflectionClass.class.php.
References createExtendedReflectionMethod().
Referenced by CodeReflectionClass::createMethodsDefinitionCode(), and CodeInstrumentationClass::createMethodsDefinitionCode().
    {
        $arrReflectionMethods = parent::getMethods( $filter );
        $arrExtendedMethods = array();
        foreach( $arrReflectionMethods as $objReflectionMethod )
        {
                /*@var $objReflectionMethod ReflectionMethod */
                $arrExtendedMethods[] = $this->createExtendedReflectionMethod( $objReflectionMethod );
        }
        return $arrExtendedMethods;
    }
getParentClass () [final]
Get the reflection of the parent class if extists and return null if not has a parent class
Returns:
ExtendedReflectionClass|null
Definition at line 28 of file ExtendedReflectionClass.class.php.
References createExtendedReflectionClass().
Referenced by CodeReflectionClass::createClassDefinitionCode().
        {
        $objParent = parent::getParentClass();
        if( $objParent != null )
        {
            return $this->createExtendedReflectionClass(  $objParent );
        }
        else
        {
            return null;
        }
        }
getProperties ($ filter = -1) [final]
Get the collection of the reflection properties of the reflected class
Parameters:
integer $filter
Returns:
ReflectionProperty[]
Definition at line 66 of file ExtendedReflectionClass.class.php.
References createExtendedReflectionProperty().
Referenced by CodeReflectionClass::createAttributesDefinitionCode().
        {
                $arrReflectionProperties = parent::getProperties( $filter );
                $arrExtendedProperties = array();
                foreach( $arrReflectionProperties as $objReflectionProperty )
                {
                        /*@var $objReflectionProperty ReflectionProperty */
                        $arrExtendedProperties[] = $this->createExtendedReflectionProperty( $objReflectionProperty );
                }
                return $arrExtendedProperties;
        }
getProperty ($ strName) [final]
Get the reflection property of some attribute of the class searched by the property name
Parameters:
string $strName
Returns:
ExtendedReflectionProperty
Definition at line 85 of file ExtendedReflectionClass.class.php.
References createExtendedReflectionProperty().
    {
        return $this->createExtendedReflectionProperty( parent::getProperty( $strName ) );
    }
The documentation for this class was generated from the following file:
components/extendedReflection/ExtendedReflectionClass.class.php