CodeToDiagram: CorujaStringManipulation Class Reference
CorujaStringManipulation Class Reference
Static Public Member Functions
static strToBool ($strText)
static forceInt ($strText)
static camelCaseToUnderlineCase ($strText)
static retab ($strText, $intDeeper)
Detailed Description
Class for string manipulations
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 11 of file CorujaStringManipulation.class.php.
Member Function Documentation
static camelCaseToUnderlineCase ($ strText) [static]
Change string case standard
Parameters:
string $strFieldName Name in camel case
Returns:
string Name in underline separated case
Exceptions:
InvalidArgumentException If $strText is not string
Example:
CorujaStringManipulation::caseTabUnderlineTab("nameOfTheParameter") // returns "NAME_OF_THE_PARAMETER"
Assert:
("test") == "TEST"
Assert:
("somethingCool") == "SOMETHING_COOL"
Assert:
("") == ""
Assert:
("1something2Cool3") == "1SOMETHING2_COOL3"
Assert:
("111something2222Cool333") == "111SOMETHING2222_COOL333"
Assert:
(null) throws InvalidArgumentException
Assert:
(123) throws InvalidArgumentException
Assert:
(array()) throws InvalidArgumentException
Assert:
(new stdClass()) throws InvalidArgumentException
Assert:
(false) throws InvalidArgumentException
Definition at line 125 of file CorujaStringManipulation.class.php.
Referenced by CorujaStringManipulationTest::testCamelCaseToUnderlineCase(), CorujaStringManipulationTest::testCamelCaseToUnderlineCase10(), CorujaStringManipulationTest::testCamelCaseToUnderlineCase2(), CorujaStringManipulationTest::testCamelCaseToUnderlineCase3(), CorujaStringManipulationTest::testCamelCaseToUnderlineCase4(), CorujaStringManipulationTest::testCamelCaseToUnderlineCase5(), CorujaStringManipulationTest::testCamelCaseToUnderlineCase6(), CorujaStringManipulationTest::testCamelCaseToUnderlineCase7(), CorujaStringManipulationTest::testCamelCaseToUnderlineCase8(), and CorujaStringManipulationTest::testCamelCaseToUnderlineCase9().
        {
                if(!is_string($strText))
                {
                        throw new InvalidArgumentException("Invalid argument [ ". var_export($strText) ." ]. It should be string");
                }
                $arrFind = Array( "A" , "B" , "C" , "D" , "E" , "F" , "G" , "H" , "I" , "J" , "K" , "L" , "M" , "N" , "O" ,
                                          "P" , "Q" , "R" , "S" , "T" , "U" , "V" , "X" , "Z" , "W" , "Y"       );
                $arrReplace = Array( "_A" , "_B" , "_C" , "_D" , "_E" , "_F" , "_G" , "_H" , "_I" , "_J" , "_K" , "_L" , "_M" ,
                                          "_N" , "_O" , "_P" , "_Q" , "_R" , "_S" , "_T" , "_U" , "_V" , "_X" , "_Z" , "_W" , "_Y"      );
                if( strlen( $strText ) > 0 )
                {
                        $strText[0] = strtolower($strText[0]);
                }
                return strtoupper( str_replace( $arrFind , $arrReplace , $strText ) );
        }
static forceInt ($ strText) [static]
Get number chars inside a string
Parameters:
string $strText Text with numbers
Returns:
int Numbers in the string
Exceptions:
InvalidArgumentException If $strText is not string
Example:
forceInt("a1b2c3d4") // returns 1234
Assert:
("a1b2c3d4") == 1234
Assert:
("") == 0
Assert:
("a0a") == 0
Assert:
("001") == 1
Assert:
("abc") == 0
Assert:
("a-10") == 10
Assert:
("-10") == -10
Assert:
("--10") == -10
Assert:
("-a-b-1-0-") == -10
Assert:
(null) throws InvalidArgumentException
Assert:
(123) throws InvalidArgumentException
Assert:
(array()) throws InvalidArgumentException
Assert:
(new stdClass()) throws InvalidArgumentException
Assert:
(false) throws InvalidArgumentException
Definition at line 79 of file CorujaStringManipulation.class.php.
Referenced by CorujaStringManipulationTest::testForceInt(), CorujaStringManipulationTest::testForceInt10(), CorujaStringManipulationTest::testForceInt11(), CorujaStringManipulationTest::testForceInt12(), CorujaStringManipulationTest::testForceInt13(), CorujaStringManipulationTest::testForceInt14(), CorujaStringManipulationTest::testForceInt2(), CorujaStringManipulationTest::testForceInt3(), CorujaStringManipulationTest::testForceInt4(), CorujaStringManipulationTest::testForceInt5(), CorujaStringManipulationTest::testForceInt6(), CorujaStringManipulationTest::testForceInt7(), CorujaStringManipulationTest::testForceInt8(), and CorujaStringManipulationTest::testForceInt9().
        {
                if(!is_string($strText))
                {
                        throw new InvalidArgumentException("Invalid argument [ ". var_export($strText) ." ]. It should be string");
                }
                $arrNum = Array( "0","1","2","3","4","5","6","7","8","9");
                $strResult = "";
                for( $i = 0; $i < strlen( $strText ); ++$i )
                {
                        $charLetra = $strText[$i];
                        if( $i == 0 && $charLetra == "-" )
{
                                $strResult .= $charLetra;
                        }
                        if( in_array($charLetra,$arrNum))
{
                                $strResult .= $charLetra;
                        }
                }
                return $strResult += 0;
        }
static retab ($ strText, $ intDeeper) [static]
Definition at line 146 of file CorujaStringManipulation.class.php.
Referenced by CodeReflectionFunction::createFunctionHeaderCode(), CodeReflectionMethod::createMethodHeaderCode(), CodeInstrumentationMethod::createMethodHeaderCode(), CodeInstrumentationMethod::getCallCodeInstrFunctionHeaderCode(), and CodeReflectionProperty::getCode().
        {
                $arrText = explode( "\n" , $strText );
                foreach( $arrText as $intKey => $strTextElement)
                {
                        $arrText [ $intKey ] = trim( $strTextElement );
                }
                $strTab = "\n" .str_repeat( "\t" , $intDeeper );
                $strText = $strTab . implode( $strTab , $arrText ) . $strTab;
                return $strText;
        }
static strToBool ($ strText) [static]
Special string casting for boolean
Parameters:
string $strText String to be turned into boolean
Returns:
boolean Input casting
Exceptions:
InvalidArgumentException If $strText is not string
Example:
strToBool("false") // returns false
Assert:
("") == false
Assert:
("false") == false
Assert:
("FaLsE") == false
Assert:
("0") == false
Assert:
("a0a") == true
Assert:
("true") == true
Assert:
("1") == true
Assert:
(null) throws InvalidArgumentException
Assert:
(123) throws InvalidArgumentException
Assert:
(array()) throws InvalidArgumentException
Assert:
(new stdClass()) throws InvalidArgumentException
Assert:
(false) throws InvalidArgumentException
Definition at line 38 of file CorujaStringManipulation.class.php.
Referenced by CorujaStringManipulationTest::testStrToBool(), CorujaStringManipulationTest::testStrToBool10(), CorujaStringManipulationTest::testStrToBool11(), CorujaStringManipulationTest::testStrToBool12(), CorujaStringManipulationTest::testStrToBool2(), CorujaStringManipulationTest::testStrToBool3(), CorujaStringManipulationTest::testStrToBool4(), CorujaStringManipulationTest::testStrToBool5(), CorujaStringManipulationTest::testStrToBool6(), CorujaStringManipulationTest::testStrToBool7(), CorujaStringManipulationTest::testStrToBool8(), and CorujaStringManipulationTest::testStrToBool9().
        {
                if(!is_string($strText))
                {
                        throw new InvalidArgumentException("Invalid argument [ ". var_export($strText) ." ]. It should be string");
                }
                $strText = strtolower( $strText );
                if ( $strText === "false" || $strText === "" || $strText === "0" )
                {
                        return( false );
                }
                return( true );
        }
The documentation for this class was generated from the following file:
components/library/CorujaStringManipulation.class.php