CodeToDiagram: Loader Class Reference
Loader Class Reference
Public Member Functions
setExternal ($booExternal)
getExternal ()
show ($strFullPathFile)
getClassContent ()
Static Public Member Functions
static getInstance ()
static requireOnce ($strFile, $booIsClass=false)
Protected Attributes
$booExternal = false
$arrFiles = array()
$strClassContent = ''
Static Protected Attributes
static $objInstance
Detailed Description
Class responsable to controls the load of the files.
This class is responsable to make the classical load of the files and to make the visible code load, what is essencial to the external load of the component.
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 16 of file Loader.class.php.
Member Function Documentation
getClassContent ()
Definition at line 122 of file Loader.class.php.
    {
        return $this->strClassContent;
    }
getExternal ()
Get if the loader it is to external access
See also:
Loader::setExternal(boolean)
Loader->boolExternal
Returns:
boolean
Definition at line 77 of file Loader.class.php.
Referenced by requireOnce().
    {
        return $this->booExternal;
    }
static getInstance () [static]
Return the singleton instance of the Loader class
Returns:
Loader
Definition at line 49 of file Loader.class.php.
Referenced by requireOnce().
    {
        if( self::$objInstance == null )
        {
            self::$objInstance = new Loader();
        }
        return self::$objInstance;
    }
static requireOnce ($ strFile, $ booIsClass = false) [static]
Require Once the file of the Code To Diagram
Parameters:
string $strFile
boolean $booIsClass
Definition at line 88 of file Loader.class.php.
References $arrBackTrace, $arrCaller, $strFileCaller, getExternal(), getInstance(), CorujaFileManipulation::getPathOfFile(), and CorujaFileManipulation::isRelativePath().
    {
//        print $strFile . '<br/>' . "\n";
        $arrBackTrace = debug_backtrace();
        $arrCaller = $arrBackTrace[0];
        $strFileCaller = $arrCaller[ 'file' ];
        $strPathCaller = CorujaFileManipulation::getPathOfFile( $strFileCaller  );
        if( CorujaFileManipulation::isRelativePath( $strFile ) )
        {
            $strFullPathFile = $strPathCaller . $strFile;
        }
        else
        {
            $strFullPathFile = $strFile;
        }
        if( $booIsClass && self::getInstance()->getExternal() )
        {
             self::getInstance()->show( $strFullPathFile );
        }
        require_once( $strFullPathFile );
    }
setExternal ($ booExternal)
Set if the loader it is to extenal access
See also:
Loader::getExternal()
Loader->boolExternal
Parameters:
boolean $booExternal
Definition at line 65 of file Loader.class.php.
References $booExternal.
    {
        $this->booExternal = $booExternal;
    }
show ($ strFullPathFile)
Definition at line 113 of file Loader.class.php.
    {
        if( !in_array( $strFullPathFile , $this->arrFiles ) )
        {
            $this->arrFiles[] = $strFullPathFile;
            $this->strClassContent .= file_get_contents( $strFullPathFile );
        }
    }
Member Data Documentation
$arrFiles = array() [protected]
Array of files already load by the lodader class
string[]
Definition at line 35 of file Loader.class.php.
$booExternal = false [protected]
Flag if the loader it is to external access
boolean
Definition at line 28 of file Loader.class.php.
Referenced by setExternal().
$objInstance [static, protected]
instance of the loader element
Loader
Definition at line 22 of file Loader.class.php.
$strClassContent = '' [protected]
Class content of the classes loaded
string
Definition at line 42 of file Loader.class.php.
The documentation for this class was generated from the following file:
components/loader/Loader.class.php