CodeToDiagram: CorujaFileManipulation Class Reference
CorujaFileManipulation Class Reference
Static Public Member Functions
static getRelativePath ($strFileFrom, $strFileTo, $booValidPath=true)
static isRelativePath ($strFile)
static getPathOfFile ($strFile)
Detailed Description
Class for manipulation of files
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 12 of file CorujaFileManipulation.class.php.
Member Function Documentation
static getPathOfFile ($ strFile) [static]
Get the path of the file
Parameters:
string $strFile
Returns:
string
Definition at line 140 of file CorujaFileManipulation.class.php.
Referenced by Loader::requireOnce(), and CodeToDiagram::setCallerPathByFile().
    {
        return str_replace( "\\" , "/" , str_replace( basename( $strFile ) , "" , $strFile ) );
    }
static getRelativePath ($ strFileFrom, $ strFileTo, $ booValidPath = true) [static]
Returns a path to a folder relative from another folder. Both parameters must be absolute.
check for valid parameters
in case paths are equal return './'
explode parameters using '/'
remove similar base folders
make final address
Parameters:
String $strFileFrom Base from the path. This must be an absolute path.
String $strFileTo Destination of the path. This must be an absolute path.
Boolean $booValidPath Use false if you don't want to check for valid folders.
Exceptions:
InvalidArgumentException In case of invalid values
Example:
$path = CorujaStringManipulation::getRelativePath("/www/folder/", "/www/another/big/"); // "../another/big/"
Assert:
("/www/folder/", "/www/another/big/", false) == "../another/big/"
Assert:
("", "") throws InvalidArgumentException
Assert:
("hello", "") throws InvalidArgumentException
Assert:
("", "hello") throws InvalidArgumentException
Assert:
("cool", "hello") throws InvalidArgumentException
Assert:
("/cool/", "hello") throws InvalidArgumentException
Assert:
("cool", "/hello/") throws InvalidArgumentException
Assert:
("/cool/", "/hello/", false) == "../hello/"
Assert:
("/cool/", "/hello/", false) == "../hello/"
Assert:
("/cool/", "/cool/", false) == "./"
Assert:
("/cool/more/", "/other/", false) == "../../other/"
Assert:
("/cool/", "/other/more/", false) == "../other/more/"
Definition at line 44 of file CorujaFileManipulation.class.php.
Referenced by XmlSequencePrinterDiagram::showHeaders().
    {
        // check for valid parameters
        $strFileFrom = str_replace( "\\" , "/" , $strFileFrom );
        $strFileTo = str_replace( "\\" , "/" , $strFileTo );
        if( $booValidPath
            && ( ! is_dir( $strFileFrom ) || ! is_dir( $strFileTo ) )
        )
        {
            throw new InvalidArgumentException("Invalid parameter: strFileFrom: ".$strFileFrom." strFileTo: ".$strFileTo);
        }
        // special case: equal paths
        if( $strFileFrom == $strFileTo )
        {
             $strReturnPath = './';
        }
        else
        {
            // explode parameters using '/'
            $arrFileFrom = explode( '/', $strFileFrom );
            $arrFileTo   = explode( '/', $strFileTo );
            // remove similar base folders
            while(
                current( $arrFileFrom ) == current( $arrFileTo )
                && count( $arrFileFrom ) > 0
            )
            {
                array_shift( $arrFileFrom );
                array_shift( $arrFileTo );
            }
            $arrReturnPath = array();
            // make final address
            foreach( $arrFileFrom as $strFolder )
            {
                if( $strFolder != "" ) {
                    $arrReturnPath[] = "..";
                }
            }
            foreach( $arrFileTo as $strFolder )
            {
                $arrReturnPath[] = $strFolder;
            }
            $strReturnPath = implode( '/', $arrReturnPath );
        }
        return $strReturnPath;
    }
static isRelativePath ($ strFile) [static]
Check if a address is relative
Assert:
("c:\www\temp.php") == false
Assert:
("d:/www/temp.php") == false
Assert:
("temp.php") == true
Assert:
("./temp.php") == true
Assert:
("/www/something.php") == false
Assert:
("./www/something.php") == true
Assert:
(".\www\something.php") == true
Assert:
("..\www\something.php") == true
Assert:
("..\www\something.php") == true
Definition at line 113 of file CorujaFileManipulation.class.php.
Referenced by CodeToDiagram::loadFile(), and Loader::requireOnce().
    {
        $strFile = str_replace( "\\", "/", $strFile);
        if(
            ( strpos( $strFile, "./") === 0 )
            or
            ( strpos( $strFile, "../") === 0 )
         )
        {
            return true;
        }
        elseif( strpos( $strFile, "/") === false )
        {
            return true;
        }
        else
        {
            return false;
        }
   }
The documentation for this class was generated from the following file:
components/library/CorujaFileManipulation.class.php