CodeToDiagram: ExtendedReflectionFunction Class Reference
ExtendedReflectionFunction Class Reference
Public Member Functions
getParameters ()
Protected Member Functions
createExtendedReflectionParameter (ReflectionParameter $objReflectionParameter)
Detailed Description
Class what make possible and easy extend reflection function
Reflection classes can be a problem because the reflection methods what return objects will return the original reflection object and not the extended version of it. So it is necessary to create methods what convert the original methods to return the extended version of the objects.
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 19 of file ExtendedReflectionFunction.class.php.
Member Function Documentation
createExtendedReflectionParameter (ReflectionParameter $ objReflectionParameter) [protected]
Convert a reflection parameter into a extended reflection parameter
This is the method what should be replaced when this class be extended.
Parameters:
ReflectionParameter $objReflectionParameter
Returns:
ExtendedReflectionParameter
Reimplemented in CodeInstrumentationFunction, and CodeReflectionFunction.
Definition at line 47 of file ExtendedReflectionFunction.class.php.
Referenced by getParameters().
        {
                return new ExtendedReflectionParameter( $this->getDeclaringClass()->getName() , $this->getName() , $objReflectionParameter->getName() );
        }
getParameters () [final]
Return a list of the parameters of the reflected function
Returns:
ExtendedReflectionParameter[]
Definition at line 26 of file ExtendedReflectionFunction.class.php.
References createExtendedReflectionParameter().
Referenced by CodeReflectionFunction::createParametersCode().
    {
        $arrReflectionParameters = parent::getParameters();
        $arrExtendedParameters = array();
                foreach( $arrReflectionParameters as $objReflectionParameter )
                {
                        /*@var $objReflectionParameter ReflectionParameter */
                        $arrExtendedParameteres[] = $this->createExtendedReflectionParameter( $objReflectionParameter );
                }
                return $arrExtendedParameters;
    }
The documentation for this class was generated from the following file:
components/extendedReflection/ExtendedReflectionFunction.class.php