CodeToDiagram: public/sequence.php File Reference
sequence.php File Reference
Namespaces
namespace public
Variables
$intZoom = (integer)getArrayElement($_POST , "zoom" , 50)
$strXml = getArrayElement($_POST , "xml" , '<sequence></sequence>')
$strTitle = getArrayElement($_POST , "title" , 'Sequence Diagram')
$objXmlSequence = new XmlSequence()
Variable Documentation
$intZoom = (integer)getArrayElement($_POST , "zoom" , 50)
This file convert the http request into a sequence diagram into screen. Can be used to external access, to be test, to be a remote tool, etc.
Author:
Thiago Henrique Ramos da Mata <thiago.henrique.mata@gmail.com>
Definition at line 17 of file sequence.php.
$objXmlSequence = new XmlSequence()
Definition at line 21 of file sequence.php.
Referenced by CodeToDiagram::save().
$strTitle = getArrayElement($_POST , "title" , 'Sequence Diagram')
Definition at line 19 of file sequence.php.
$strXml = getArrayElement($_POST , "xml" , '<sequence></sequence>')
Definition at line 18 of file sequence.php.
Referenced by XmlSequencePrinterXml::createXml(), and XmlSequenceFactoryXml::setXml().