<? require_once( "default.php" )?>
<script src="../experimental/canvasBox/classDiagram/CanvasBoxClass.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/classDiagram/CanvasBoxAggregation.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/classDiagram/CanvasBoxAssociation.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/classDiagram/CanvasBoxComposition.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/classDiagram/CanvasBoxDependency.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/classDiagram/CanvasBoxGeneralization.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/classDiagram/CanvasBoxSquare.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/stateMachine/CanvasBoxState.js" type="text/javascript" charset="utf-8"'></script>
