<script src="../experimental/phpjs/php.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/prototype.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBox.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBoxConnector.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBoxDefaultBehavior.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBoxDefaultConnectorBehavior.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBoxElement.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBoxGravityBehavior.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBoxLine.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBoxMagneticBehavior.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBoxMagneticConnectorBehavior.js" type="text/javascript" charset="utf-8"></script>
<script src="../experimental/canvasBox/default/CanvasBoxMenu.js" type="text/javascript" charset="utf-8"></script>